# Epoch/Round Tuning Analysis

This notebook analyzes TinyLlama epoch/round tuning on the four instruction datasets used in the thesis chapter: Dolly, Dolly stratified, Wizard, and Wizard stratified. It compares Linear FLoRA, cumulative Nonlinear FLoRA, and Nonlinear FFA under Homo and Heter settings with three decision views: absolute best accuracy, compute-efficient near-best accuracy, and communication-efficient near-best accuracy. RTE rows are intentionally excluded from the thesis-facing instruction-dataset tables and plots, then reported separately in the independent RTE RoBERTa section below.

In [32]:
import os
import re
from pathlib import Path

from IPython.display import display
import pandas as pd
import plotly.express as px

from utils.tuning_analysis import (
    build_extension_requests,
    build_llama_confirmation_requests,
    compare_selected_to_paper,
    compute_epoch_round_selection_metrics,
    load_live_tuning_results,
    load_tuning_results,
    make_tuning_heatmap,
    make_tuning_round_curves,
    select_plateaus,
    summarize_tuning_results,
    write_manifest,
)

CHROME_PATH = Path.home() / '.cache' / 'plotly-chrome' / 'chrome-linux64' / 'chrome'
if CHROME_PATH.exists():
    os.environ.setdefault('BROWSER_PATH', str(CHROME_PATH))

BASE_DIR = Path('.')
INSTRUCTION_DATASETS = ['dolly', 'dolly_stratified', 'wiz', 'wiz_stratified']
INSTRUCTION_DATASET_LABELS = {
    'dolly': 'Dolly',
    'dolly_stratified': 'Dolly stratified',
    'wiz': 'Wizard',
    'wiz_stratified': 'Wizard stratified',
}
NEAR_BEST_TOLERANCE = 1.0
SWITCH_GAIN_THRESHOLD = 0.5

NONLINEAR_FLORA_MANIFEST = BASE_DIR / 'tuning_manifests' / 'tinyllama_nonlinear_flora_stratified_seed0_r10.tsv'
CUMULATIVE_NONLINEAR_FLORA_RUN_ROOT = BASE_DIR / 'epoch_round_tuning_nonlinear_flora_cumulative'
LIVE_LOG_DIR = BASE_DIR / 'logs'
TUNING_RUN_ROOTS = [
    BASE_DIR / 'epoch_round_tuning',
    BASE_DIR / 'epoch_round_tuning_r10',
    BASE_DIR / 'epoch_round_tuning_dolly_dirichlet_r10',
    BASE_DIR / 'exp2-tinyllama-nonlinear-wiz',
    BASE_DIR / 'exp2-tinyllama-nonlinear-3round-heter-wiz',
    BASE_DIR / 'epoch_round_tuning_wiz_stratified_r10',
    # BASE_DIR / 'exp2-llama-nonlinear-1round-homo-wiz',
    # BASE_DIR / 'exp2-llama-nonlinear-1round-heter-wiz',
]
CENTRALIZED_LORA_RUNS = [
    {
        'dataset': 'dolly_stratified',
        'model': 'tinyllama',
        'epochs': 3,
        'metrics_path': Path('/home/trieu.vy.tran/LoRA/examples/NLU/centralized_instruction_qa/full/dolly_tinyllama_seed0/metrics.json'),
    },
    {
        'dataset': 'wiz_stratified',
        'model': 'tinyllama',
        'epochs': 3,
        'metrics_path': Path('/home/trieu.vy.tran/LoRA/examples/NLU/centralized_instruction_qa/full/wizard_tinyllama_seed0/metrics.json'),
    },
]
OUTPUT_DIR = BASE_DIR / 'tuning_analysis_outputs'
FIGURE_DIR = OUTPUT_DIR / 'epoch_round_heatmaps'
ROUND_CURVE_DIR = BASE_DIR / 'plots_epoch_round_tuning'
DYNAMIC_EPOCH_DIR = ROUND_CURVE_DIR / 'dynamic_epoch_oracle'

OUTPUT_DIR.mkdir(exist_ok=True)
FIGURE_DIR.mkdir(exist_ok=True)
ROUND_CURVE_DIR.mkdir(exist_ok=True)
DYNAMIC_EPOCH_DIR.mkdir(exist_ok=True)

## Load And Select

In [33]:
import importlib
import utils.tuning_analysis as tuning_analysis

tuning_analysis = importlib.reload(tuning_analysis)
load_live_tuning_results = tuning_analysis.load_live_tuning_results
load_tuning_results = tuning_analysis.load_tuning_results
summarize_tuning_results = tuning_analysis.summarize_tuning_results
select_plateaus = tuning_analysis.select_plateaus
compute_epoch_round_selection_metrics = tuning_analysis.compute_epoch_round_selection_metrics
make_tuning_heatmap = tuning_analysis.make_tuning_heatmap

RUN_ID_COLUMNS = ['Method key', 'Dataset', 'Model key', 'Setting key', 'Local epochs', 'Seed']


def _instruction_filter(frame):
    if frame is None or frame.empty or 'Dataset' not in frame.columns:
        return frame.copy() if frame is not None else frame
    return frame[frame['Dataset'].isin(INSTRUCTION_DATASETS)].copy()


def _manifest_model_tag(model):
    return 'llama' if model in {'llama', 'llama-7b'} else str(model)


def _manifest_log_path(row, run_root):
    method = str(row['method'])
    model = _manifest_model_tag(str(row['model']))
    epochs = int(row['epochs'])
    rounds = int(row['rounds'])
    seed = int(row['seed'])
    run_dir = run_root / f"tuning-{method}-{row['dataset']}-{model}-{row['setting']}-e{epochs}-r{rounds}" / f"seed{seed}"
    if method == 'flora':
        return run_dir / '10log.txt'
    return run_dir / '10' / 'log.txt'


def _live_observed_rounds(live_scores, row):
    if live_scores is None or live_scores.empty:
        return 0
    model = 'llama' if str(row['model']) in {'llama', 'llama-7b'} else str(row['model'])
    matches = live_scores[
        (live_scores['Method key'] == str(row['method']))
        & (live_scores['Dataset'] == str(row['dataset']))
        & (live_scores['Model key'] == model)
        & (live_scores['Setting key'] == str(row['setting']))
        & (live_scores['Local epochs'].astype(int) == int(row['epochs']))
        & (live_scores['Seed'].astype(int) == int(row['seed']))
    ]
    if matches.empty:
        return 0
    return int(matches['Round'].max())


def build_manifest_status(manifest_path, run_root, live_scores=None):
    if not manifest_path.exists():
        return pd.DataFrame()

    status_rows = []
    manifest = pd.read_csv(manifest_path, sep='	')
    for _, row in manifest.iterrows():
        log_path = _manifest_log_path(row, run_root)
        observed_rounds = 0
        result_source = 'none'
        if log_path.exists():
            observed_rounds = sum(1 for line in log_path.read_text().splitlines() if line.strip())
            result_source = 'score log'
        else:
            observed_rounds = _live_observed_rounds(live_scores, row)
            if observed_rounds:
                result_source = 'slurm stdout'
        config_rounds = int(row['rounds'])
        complete_run = observed_rounds >= config_rounds and result_source == 'score log'
        status = 'complete' if complete_run else ('censored partial' if observed_rounds else 'missing')
        status_rows.append(
            {
                'Method': row['method'],
                'Dataset': row['dataset'],
                'Dataset label': INSTRUCTION_DATASET_LABELS.get(row['dataset'], row['dataset']),
                'Model': row['model'],
                'Setting': row['setting'],
                'Local epochs': int(row['epochs']),
                'Config rounds': config_rounds,
                'Seed': int(row['seed']),
                'Observed rounds': observed_rounds,
                'Complete run': complete_run,
                'Status': status,
                'Analysis use': 'selection + plots' if complete_run else ('plots only' if observed_rounds else 'not used'),
                'Result source': result_source,
                'Log path': str(log_path),
            }
        )
    return pd.DataFrame(status_rows)


def build_cumulative_run_status(run_root, live_scores=None):
    status_rows = []
    if not run_root.exists():
        return pd.DataFrame()

    for run_dir in sorted(run_root.glob('tuning-nonlinear_flora-*')):
        match = tuning_analysis.RUN_DIR_RE.match(run_dir.name)
        if not match:
            continue
        info = match.groupdict()
        if info['dataset'] not in INSTRUCTION_DATASETS:
            continue
        for seed_dir in sorted(run_dir.glob('seed*')):
            seed_text = seed_dir.name.removeprefix('seed')
            if not seed_text.isdigit():
                continue
            row = {
                'method': info['method'],
                'dataset': info['dataset'],
                'model': 'llama' if info['model'] == 'llama-7b' else info['model'],
                'setting': info['setting'],
                'epochs': int(info['epochs']),
                'rounds': int(info['rounds']),
                'seed': int(seed_text),
            }
            log_path = seed_dir / '10' / 'log.txt'
            observed_rounds = 0
            result_source = 'none'
            if log_path.exists():
                observed_rounds = sum(1 for line in log_path.read_text().splitlines() if line.strip())
                result_source = 'score log'
            else:
                observed_rounds = _live_observed_rounds(live_scores, row)
                if observed_rounds:
                    result_source = 'slurm stdout'
            complete_run = observed_rounds >= int(info['rounds']) and result_source == 'score log'
            status = 'complete' if complete_run else ('censored partial' if observed_rounds else 'missing')
            status_rows.append(
                {
                    'Method key': info['method'],
                    'Method': 'Nonlinear FLoRA',
                    'Dataset': info['dataset'],
                    'Dataset label': INSTRUCTION_DATASET_LABELS.get(info['dataset'], info['dataset']),
                    'Model key': row['model'],
                    'Model': 'TinyLlama' if row['model'] == 'tinyllama' else row['model'],
                    'Setting key': info['setting'],
                    'Setting': 'Homo' if info['setting'] == 'homo' else 'Heter',
                    'Local epochs': int(info['epochs']),
                    'Config rounds': int(info['rounds']),
                    'Seed': int(seed_text),
                    'Observed rounds': observed_rounds,
                    'Complete run': complete_run,
                    'Status': status,
                    'Analysis use': 'selection + plots' if complete_run else ('plots only' if observed_rounds else 'not used'),
                    'Result source': result_source,
                    'Log path': str(log_path),
                }
            )
    return pd.DataFrame(status_rows)


def _normalize_run_id_types(frame):
    if frame is None or frame.empty:
        return frame.copy() if frame is not None else frame
    data = frame.copy()
    for column in ['Local epochs', 'Seed']:
        if column in data.columns:
            data[column] = data[column].astype(int)
    return data


def _filter_live_preview_to_incomplete(live_scores, complete_scores):
    preview = _instruction_filter(live_scores)
    if preview is None or preview.empty:
        return pd.DataFrame(columns=live_scores.columns if live_scores is not None else [])

    preview = _normalize_run_id_types(preview)
    preview['Method key'] = 'nonlinear_flora'
    preview['Method'] = 'Nonlinear FLoRA'
    preview['Run status'] = 'Censored partial'

    complete = _normalize_run_id_types(_instruction_filter(complete_scores))
    if complete is not None and not complete.empty:
        complete_keys = complete[RUN_ID_COLUMNS].drop_duplicates().assign(_has_complete=True)
        preview = preview.merge(complete_keys, on=RUN_ID_COLUMNS, how='left')
        preview = preview[preview['_has_complete'].isna()].drop(columns=['_has_complete'])

    return preview.copy()


# Complete-run tables use score logs only. Old nonlinear FLoRA complete runs are
# excluded because those runs used the overwrite behavior; cumulative nonlinear
# FLoRA score logs are included as the valid Nonlinear FLoRA source.
live_scores = load_live_tuning_results(
    LIVE_LOG_DIR,
    run_roots=CUMULATIVE_NONLINEAR_FLORA_RUN_ROOT,
)

raw_complete_scores = load_tuning_results(TUNING_RUN_ROOTS, complete_only=True)
obsolete_nonlinear_mask = raw_complete_scores['Method key'].eq('nonlinear_flora') if not raw_complete_scores.empty else pd.Series(dtype=bool)
standard_complete_scores = raw_complete_scores.loc[~obsolete_nonlinear_mask].copy() if not raw_complete_scores.empty else raw_complete_scores
cumulative_complete_scores = load_tuning_results(CUMULATIVE_NONLINEAR_FLORA_RUN_ROOT, complete_only=True)
cumulative_complete_scores = _instruction_filter(cumulative_complete_scores)

cumulative_nonlinear_flora_status = build_cumulative_run_status(
    CUMULATIVE_NONLINEAR_FLORA_RUN_ROOT,
    live_scores=live_scores,
)

live_preview_scores = _filter_live_preview_to_incomplete(
    live_scores,
    cumulative_complete_scores,
)

tuning_scores = pd.concat(
    [standard_complete_scores, cumulative_complete_scores],
    ignore_index=True,
    sort=False,
)
tuning_scores = _instruction_filter(tuning_scores)
tuning_summary = summarize_tuning_results(tuning_scores)
tuning_plateaus, tuning_selected = select_plateaus(tuning_summary, tolerance=NEAR_BEST_TOLERANCE)
curve_diagnostics, optimal_epoch_round_pairs, marginal_round_gains = compute_epoch_round_selection_metrics(
    tuning_summary,
    plateaus=tuning_plateaus,
    selected_pairs=tuning_selected,
    tolerance=NEAR_BEST_TOLERANCE,
)

# Plot-only preview data includes censored cumulative nonlinear FLoRA rows from
# Slurm stdout only when the final score log is absent.
plot_scores = pd.concat([tuning_scores, live_preview_scores], ignore_index=True, sort=False)
plot_scores = _instruction_filter(plot_scores)
plot_summary = summarize_tuning_results(plot_scores)

run_count = tuning_scores['Run dir'].nunique() if not tuning_scores.empty else 0
case_count = tuning_selected.shape[0] if not tuning_selected.empty else 0
live_run_count = live_preview_scores['Run dir'].nunique() if not live_preview_scores.empty else 0
cumulative_complete_run_count = cumulative_complete_scores['Run dir'].nunique() if not cumulative_complete_scores.empty else 0
obsolete_nonlinear_run_count = raw_complete_scores.loc[obsolete_nonlinear_mask, 'Run dir'].nunique() if not raw_complete_scores.empty else 0
expected_cases = len(INSTRUCTION_DATASETS) * 2 * 3
print(f'Loaded {len(tuning_scores)} per-round scores from {run_count} complete instruction-dataset runs.')
print(f'Included {cumulative_complete_run_count} cumulative Nonlinear FLoRA complete runs.')
print(f'Excluded {obsolete_nonlinear_run_count} old nonlinear FLoRA complete runs with overwrite behavior.')
print(f'Loaded {len(live_preview_scores)} censored plot-only scores from {live_run_count} cumulative Nonlinear FLoRA runs.')
print(f'Selected {case_count}/{expected_cases} method/dataset/model/setting configurations from complete runs only.')

if cumulative_nonlinear_flora_status.empty:
    print(f'No cumulative nonlinear FLoRA status found under {CUMULATIVE_NONLINEAR_FLORA_RUN_ROOT}.')
else:
    display(
        cumulative_nonlinear_flora_status
        .drop(columns=['Log path'])
        .sort_values(['Dataset label', 'Setting', 'Local epochs'])
        .reset_index(drop=True)
    )

display(tuning_selected.round(2))
display(tuning_plateaus.round(2))

Loaded 940 per-round scores from 94 complete instruction-dataset runs.
Included 30 cumulative Nonlinear FLoRA complete runs.
Excluded 23 old nonlinear FLoRA complete runs with overwrite behavior.
Loaded 14 censored plot-only scores from 2 cumulative Nonlinear FLoRA runs.
Selected 24/24 method/dataset/model/setting configurations from complete runs only.

,Method key,Method,Dataset,Dataset label,Model key,Model,Setting key,Setting,Local epochs,Config rounds,Seed,Observed rounds,Complete run,Status,Analysis use,Result source
0,nonlinear_flora,Nonlinear FLoRA,dolly,Dolly,tinyllama,TinyLlama,heter,Heter,1,10,0,10,True,complete,selection + plots,score log
1,nonlinear_flora,Nonlinear FLoRA,dolly,Dolly,tinyllama,TinyLlama,heter,Heter,2,10,0,10,True,complete,selection + plots,score log
2,nonlinear_flora,Nonlinear FLoRA,dolly,Dolly,tinyllama,TinyLlama,heter,Heter,3,10,0,10,True,complete,selection + plots,score log
3,nonlinear_flora,Nonlinear FLoRA,dolly,Dolly,tinyllama,TinyLlama,heter,Heter,5,10,0,10,True,complete,selection + plots,score log
4,nonlinear_flora,Nonlinear FLoRA,dolly,Dolly,tinyllama,TinyLlama,homo,Homo,1,10,0,10,True,complete,selection + plots,score log
5,nonlinear_flora,Nonlinear FLoRA,dolly,Dolly,tinyllama,TinyLlama,homo,Homo,2,10,0,10,True,complete,selection + plots,score log
6,nonlinear_flora,Nonlinear FLoRA,dolly,Dolly,tinyllama,TinyLlama,homo,Homo,3,10,0,10,True,complete,selection + plots,score log
7,nonlinear_flora,Nonlinear FLoRA,dolly,Dolly,tinyllama,TinyLlama,homo,Homo,5,10,0,10,True,complete,selection + plots,score log
8,nonlinear_flora,Nonlinear FLoRA,dolly_stratified,Dolly stratified,tinyllama,TinyLlama,heter,Heter,1,10,0,10,True,complete,selection + plots,score log
9,nonlinear_flora,Nonlinear FLoRA,dolly_stratified,Dolly stratified,tinyllama,TinyLlama,heter,Heter,2,10,0,10,True,complete,selection + plots,score log
10,nonlinear_flora,Nonlinear FLoRA,dolly_stratified,Dolly stratified,tinyllama,TinyLlama,heter,Heter,3,10,0,10,True,complete,selection + plots,score log
11,nonlinear_flora,Nonlinear FLoRA,dolly_stratified,Dolly stratified,tinyllama,TinyLlama,heter,Heter,5,10,0,10,True,complete,selection + plots,score log
12,nonlinear_flora,Nonlinear FLoRA,dolly_stratified,Dolly stratified,tinyllama,TinyLlama,homo,Homo,1,10,0,10,True,complete,selection + plots,score log
13,nonlinear_flora,Nonlinear FLoRA,dolly_stratified,Dolly stratified,tinyllama,TinyLlama,homo,Homo,2,10,0,10,True,complete,selection + plots,score log
14,nonlinear_flora,Nonlinear FLoRA,dolly_stratified,Dolly stratified,tinyllama,TinyLlama,homo,Homo,3,10,0,10,True,complete,selection + plots,score log
15,nonlinear_flora,Nonlinear FLoRA,dolly_stratified,Dolly stratified,tinyllama,TinyLlama,homo,Homo,5,10,0,10,True,complete,selection + plots,score log
16,nonlinear_flora,Nonlinear FLoRA,wiz,Wizard,tinyllama,TinyLlama,heter,Heter,1,10,0,10,True,complete,selection + plots,score log
17,nonlinear_flora,Nonlinear FLoRA,wiz,Wizard,tinyllama,TinyLlama,heter,Heter,2,10,0,10,True,complete,selection + plots,score log
18,nonlinear_flora,Nonlinear FLoRA,wiz,Wizard,tinyllama,TinyLlama,heter,Heter,3,10,0,10,True,complete,selection + plots,score log
19,nonlinear_flora,Nonlinear FLoRA,wiz,Wizard,tinyllama,TinyLlama,heter,Heter,5,10,0,10,True,complete,selection + plots,score log
20,nonlinear_flora,Nonlinear FLoRA,wiz,Wizard,tinyllama,TinyLlama,homo,Homo,1,10,0,10,True,complete,selection + plots,score log
21,nonlinear_flora,Nonlinear FLoRA,wiz,Wizard,tinyllama,TinyLlama,homo,Homo,2,10,0,10,True,complete,selection + plots,score log
22,nonlinear_flora,Nonlinear FLoRA,wiz,Wizard,tinyllama,TinyLlama,homo,Homo,3,10,0,10,True,complete,selection + plots,score log
23,nonlinear_flora,Nonlinear FLoRA,wiz,Wizard,tinyllama,TinyLlama,homo,Homo,5,10,0,10,True,complete,selection + plots,score log
24,nonlinear_flora,Nonlinear FLoRA,wiz_stratified,Wizard stratified,tinyllama,TinyLlama,heter,Heter,1,10,0,10,True,complete,selection + plots,score log
25,nonlinear_flora,Nonlinear FLoRA,wiz_stratified,Wizard stratified,tinyllama,TinyLlama,heter,Heter,2,10,0,10,True,complete,selection + plots,score log
26,nonlinear_flora,Nonlinear FLoRA,wiz_stratified,Wizard stratified,tinyllama,TinyLlama,heter,Heter,3,10,0,10,True,complete,selection + plots,score log
27,nonlinear_flora,Nonlinear FLoRA,wiz_stratified,Wizard stratified,tinyllama,TinyLlama,heter,Heter,5,10,0,7,False,censored partial,plots only,slurm stdout
28,nonlinear_flora,Nonlinear FLoRA,wiz_stratified,Wizard stratified,tinyllama,TinyLlama,homo,Homo,1,10,0,10,True,complete,selection + plots,score log
29,nonlinear_flora,Nonlinear FLoRA,wiz_stratified,Wizard stratified,tinyllama,TinyLlama,homo,Homo,2,10,0,10,True,complete,selection + plots,score log
30,nonlinear_flora,Nonlinear FLoRA,wiz_stratified,Wizard stratified,tinyllama,TinyLlama,homo,Homo,3,10,0,10,True,complete,selection + plots,score log
31,nonlinear_flora,Nonlinear FLoRA,wiz_stratified,Wizard stratified,tinyllama,TinyLlama,homo,Homo,5,10,0,7,False,censored partial,plots only,slurm stdout

,Method key,Method,Dataset,Dataset label,Model key,Model,Setting key,Setting,Selected epochs,Selected round,Selected accuracy,Selected std,Selected seed count,Selected seeds,Selected compute cost,Best epochs,Best round,Best accuracy,Accuracy gap to best,Low-cost tie count
0,ffa,Nonlinear FFA,dolly,Dolly,tinyllama,TinyLlama,heter,Heter,3,4,28.52,0.0,1,0,12,5,9,29.05,0.52,1
1,ffa,Nonlinear FFA,dolly,Dolly,tinyllama,TinyLlama,homo,Homo,2,3,29.90,0.0,1,0,6,5,7,30.87,0.97,1
6,ffa,Nonlinear FFA,dolly_stratified,Dolly stratified,tinyllama,TinyLlama,heter,Heter,3,5,29.62,0.0,1,0,15,3,5,29.62,0.00,1
7,ffa,Nonlinear FFA,dolly_stratified,Dolly stratified,tinyllama,TinyLlama,homo,Homo,3,7,30.62,0.0,1,0,21,3,10,31.26,0.65,1
12,ffa,Nonlinear FFA,wiz,Wizard,tinyllama,TinyLlama,heter,Heter,1,6,33.19,0.0,1,0,6,1,10,33.63,0.44,1
13,ffa,Nonlinear FFA,wiz,Wizard,tinyllama,TinyLlama,homo,Homo,2,1,30.69,0.0,1,0,2,5,4,31.55,0.86,2
18,ffa,Nonlinear FFA,wiz_stratified,Wizard stratified,tinyllama,TinyLlama,heter,Heter,2,3,32.46,0.0,1,0,6,5,3,33.37,0.91,1
19,ffa,Nonlinear FFA,wiz_stratified,Wizard stratified,tinyllama,TinyLlama,homo,Homo,2,2,31.81,0.0,1,0,4,5,1,32.35,0.54,1
2,flora,Linear FLoRA,dolly,Dolly,tinyllama,TinyLlama,heter,Heter,2,1,29.38,0.0,1,0,2,2,5,29.96,0.58,1
3,flora,Linear FLoRA,dolly,Dolly,tinyllama,TinyLlama,homo,Homo,3,2,31.03,0.0,1,0,6,3,2,31.03,0.00,1
8,flora,Linear FLoRA,dolly_stratified,Dolly stratified,tinyllama,TinyLlama,heter,Heter,5,1,28.34,0.0,1,0,5,2,8,29.11,0.77,1
9,flora,Linear FLoRA,dolly_stratified,Dolly stratified,tinyllama,TinyLlama,homo,Homo,1,5,28.63,0.0,1,0,5,5,4,29.61,0.98,1
14,flora,Linear FLoRA,wiz,Wizard,tinyllama,TinyLlama,heter,Heter,3,1,46.22,0.0,1,0,3,3,1,46.22,0.00,1
15,flora,Linear FLoRA,wiz,Wizard,tinyllama,TinyLlama,homo,Homo,1,1,45.10,0.0,1,0,1,1,1,45.10,0.00,1
20,flora,Linear FLoRA,wiz_stratified,Wizard stratified,tinyllama,TinyLlama,heter,Heter,3,1,45.74,0.0,1,0,3,3,1,45.74,0.00,1
21,flora,Linear FLoRA,wiz_stratified,Wizard stratified,tinyllama,TinyLlama,homo,Homo,1,1,46.74,0.0,1,0,1,1,1,46.74,0.00,1
4,nonlinear_flora,Nonlinear FLoRA,dolly,Dolly,tinyllama,TinyLlama,heter,Heter,2,4,30.10,0.0,1,0,8,3,3,31.06,0.96,1
5,nonlinear_flora,Nonlinear FLoRA,dolly,Dolly,tinyllama,TinyLlama,homo,Homo,3,3,30.22,0.0,1,0,9,3,3,30.22,0.00,1
10,nonlinear_flora,Nonlinear FLoRA,dolly_stratified,Dolly stratified,tinyllama,TinyLlama,heter,Heter,3,2,30.10,0.0,1,0,6,3,2,30.10,0.00,1
11,nonlinear_flora,Nonlinear FLoRA,dolly_stratified,Dolly stratified,tinyllama,TinyLlama,homo,Homo,2,6,29.71,0.0,1,0,12,2,6,29.71,0.00,1
16,nonlinear_flora,Nonlinear FLoRA,wiz,Wizard,tinyllama,TinyLlama,heter,Heter,3,1,44.13,0.0,1,0,3,3,1,44.13,0.00,1
17,nonlinear_flora,Nonlinear FLoRA,wiz,Wizard,tinyllama,TinyLlama,homo,Homo,2,1,42.02,0.0,1,0,2,2,1,42.02,0.00,1
22,nonlinear_flora,Nonlinear FLoRA,wiz_stratified,Wizard stratified,tinyllama,TinyLlama,heter,Heter,3,1,45.38,0.0,1,0,3,3,1,45.38,0.00,1
23,nonlinear_flora,Nonlinear FLoRA,wiz_stratified,Wizard stratified,tinyllama,TinyLlama,homo,Homo,2,3,42.88,0.0,1,0,6,2,3,42.88,0.00,1

,Method key,Method,Dataset,Dataset label,Model key,Model,Setting key,Setting,Local epochs,Plateau round,Plateau accuracy,Best round,Best accuracy,Max round observed,Declined after best
0,ffa,Nonlinear FFA,dolly,Dolly,tinyllama,TinyLlama,heter,Heter,1,8,26.33,10,27.24,10,False
1,ffa,Nonlinear FFA,dolly,Dolly,tinyllama,TinyLlama,heter,Heter,2,7,27.52,9,28.38,10,False
2,ffa,Nonlinear FFA,dolly,Dolly,tinyllama,TinyLlama,heter,Heter,3,4,28.52,6,28.99,10,True
3,ffa,Nonlinear FFA,dolly,Dolly,tinyllama,TinyLlama,heter,Heter,5,4,28.88,9,29.05,10,True
4,ffa,Nonlinear FFA,dolly,Dolly,tinyllama,TinyLlama,homo,Homo,1,6,29.29,6,29.29,10,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,nonlinear_flora,Nonlinear FLoRA,wiz_stratified,Wizard stratified,tinyllama,TinyLlama,heter,Heter,2,2,43.75,2,43.75,10,True
90,nonlinear_flora,Nonlinear FLoRA,wiz_stratified,Wizard stratified,tinyllama,TinyLlama,heter,Heter,3,1,45.38,1,45.38,10,True
91,nonlinear_flora,Nonlinear FLoRA,wiz_stratified,Wizard stratified,tinyllama,TinyLlama,homo,Homo,1,10,41.17,10,41.17,10,False
92,nonlinear_flora,Nonlinear FLoRA,wiz_stratified,Wizard stratified,tinyllama,TinyLlama,homo,Homo,2,3,42.88,3,42.88,10,True
93,nonlinear_flora,Nonlinear FLoRA,wiz_stratified,Wizard stratified,tinyllama,TinyLlama,homo,Homo,3,1,41.80,1,41.80,10,True

In [34]:
tuning_scores.to_csv(OUTPUT_DIR / 'tuning_scores.csv', index=False)
tuning_summary.to_csv(OUTPUT_DIR / 'tuning_summary.csv', index=False)
tuning_plateaus.to_csv(OUTPUT_DIR / 'tuning_plateaus.csv', index=False)
tuning_selected.to_csv(OUTPUT_DIR / 'tuning_selected.csv', index=False)
curve_diagnostics.to_csv(OUTPUT_DIR / 'epoch_round_curve_diagnostics.csv', index=False)
optimal_epoch_round_pairs.to_csv(OUTPUT_DIR / 'epoch_round_optimal_pairs.csv', index=False)
marginal_round_gains.to_csv(OUTPUT_DIR / 'epoch_round_marginal_gains.csv', index=False)
cumulative_nonlinear_flora_status.to_csv(OUTPUT_DIR / 'cumulative_nonlinear_flora_status.csv', index=False)
live_preview_scores.to_csv(OUTPUT_DIR / 'censored_plot_only_scores.csv', index=False)
print(f'Wrote instruction-dataset CSV summaries to {OUTPUT_DIR}.')

Wrote instruction-dataset CSV summaries to tuning_analysis_outputs.

## Optimal Epoch/Round Metrics

In [35]:
OPTIMAL_DISPLAY_COLUMNS = [
    'Method',
    'Dataset label',
    'Setting',
    'Selected epochs',
    'Selected round',
    'Selected accuracy',
    'Selected compute cost',
    'Selected post-peak degradation',
    'Best epochs',
    'Best round',
    'Best accuracy',
    'Accuracy gap to best',
    'Communication-efficient epochs',
    'Communication-efficient round',
    'Communication-efficient accuracy',
    'Communication-efficient compute cost',
    'Communication-efficient gap to best',
    'Selection matches tuning_selected',
]
DIAGNOSTIC_DISPLAY_COLUMNS = [
    'Method',
    'Dataset label',
    'Setting',
    'Local epochs',
    'Plateau round',
    'Plateau accuracy',
    'Best round',
    'Best accuracy',
    'Final round',
    'Final accuracy',
    'Post-peak degradation',
    'Worst later degradation',
    'Later rounds hurt > tolerance',
]
MARGINAL_SUMMARY_COLUMNS = [
    'Method',
    'Dataset label',
    'Setting',
    'Local epochs',
    'Mean marginal gain',
    'Last marginal gain',
    'Negative marginal rounds',
]
METHOD_KEY_LABELS = {
    'flora': 'Linear FLoRA',
    'nonlinear_flora': 'Nonlinear FLoRA',
    'ffa': 'Nonlinear FFA',
}


def _method_rows(frame, method_key):
    if frame.empty:
        return frame
    return frame[frame['Method key'].eq(method_key)].copy()


def _display_optimal_metrics(method_key, label):
    optimal_rows = _method_rows(optimal_epoch_round_pairs, method_key)
    diagnostic_rows = _method_rows(curve_diagnostics, method_key)
    marginal_rows = _method_rows(marginal_round_gains, method_key)

    print(f'{label}: efficient optimal epoch/round pairs within {NEAR_BEST_TOLERANCE:.1f} percentage point of best')
    if optimal_rows.empty:
        print(f'No complete-run {label} rows available.')
    else:
        display(
            optimal_rows[OPTIMAL_DISPLAY_COLUMNS]
            .sort_values(['Dataset label', 'Setting'])
            .reset_index(drop=True)
            .round(2)
        )

    print(f'{label}: per-epoch plateau and degradation diagnostics')
    if diagnostic_rows.empty:
        print(f'No complete-run {label} diagnostics available.')
    else:
        display(
            diagnostic_rows[DIAGNOSTIC_DISPLAY_COLUMNS]
            .sort_values(['Dataset label', 'Setting', 'Local epochs'])
            .reset_index(drop=True)
            .round(2)
        )

    print(f'{label}: marginal round-gain summary')
    if marginal_rows.empty:
        print(f'No complete-run {label} marginal gains available.')
    else:
        marginal_summary = (
            marginal_rows
            .sort_values(['Dataset label', 'Setting', 'Local epochs', 'Round'])
            .groupby(['Method', 'Dataset label', 'Setting', 'Local epochs'], as_index=False)
            .agg(
                **{
                    'Mean marginal gain': ('Marginal accuracy gain', 'mean'),
                    'Last marginal gain': ('Marginal accuracy gain', 'last'),
                    'Negative marginal rounds': ('Marginal accuracy gain', lambda values: int((values < 0).sum())),
                }
            )
        )
        display(marginal_summary[MARGINAL_SUMMARY_COLUMNS].round(2))


print('Optimal metrics are computed from complete score logs only; censored Nonlinear FLoRA rows stay plot-only.')
for method_key, label in METHOD_KEY_LABELS.items():
    _display_optimal_metrics(method_key, label)

if optimal_epoch_round_pairs.empty:
    print('No reusable all-method optimal table available.')
else:
    print('All complete-run methods: reusable optimal-pair table')
    display(
        optimal_epoch_round_pairs[OPTIMAL_DISPLAY_COLUMNS]
        .sort_values(['Dataset label', 'Setting', 'Method'])
        .reset_index(drop=True)
        .round(2)
    )

Optimal metrics are computed from complete score logs only; censored Nonlinear FLoRA rows stay plot-only.
Linear FLoRA: efficient optimal epoch/round pairs within 1.0 percentage point of best

,Method,Dataset label,Setting,Selected epochs,Selected round,Selected accuracy,Selected compute cost,Selected post-peak degradation,Best epochs,Best round,Best accuracy,Accuracy gap to best,Communication-efficient epochs,Communication-efficient round,Communication-efficient accuracy,Communication-efficient compute cost,Communication-efficient gap to best,Selection matches tuning_selected
0,Linear FLoRA,Dolly,Heter,2,1,29.38,2,1.12,2,5,29.96,0.58,2,1,29.38,2,0.58,True
1,Linear FLoRA,Dolly,Homo,3,2,31.03,6,2.78,3,2,31.03,0.00,3,2,31.03,6,0.00,True
2,Linear FLoRA,Dolly stratified,Heter,5,1,28.34,5,3.25,2,8,29.11,0.77,5,1,28.34,5,0.77,True
3,Linear FLoRA,Dolly stratified,Homo,1,5,28.63,5,0.67,5,4,29.61,0.98,3,2,28.85,6,0.77,True
4,Linear FLoRA,Wizard,Heter,3,1,46.22,3,7.88,3,1,46.22,0.00,3,1,46.22,3,0.00,True
5,Linear FLoRA,Wizard,Homo,1,1,45.10,1,9.52,1,1,45.10,0.00,1,1,45.10,1,0.00,True
6,Linear FLoRA,Wizard stratified,Heter,3,1,45.74,3,9.92,3,1,45.74,0.00,3,1,45.74,3,0.00,True
7,Linear FLoRA,Wizard stratified,Homo,1,1,46.74,1,11.40,1,1,46.74,0.00,1,1,46.74,1,0.00,True

Linear FLoRA: per-epoch plateau and degradation diagnostics

,Method,Dataset label,Setting,Local epochs,Plateau round,Plateau accuracy,Best round,Best accuracy,Final round,Final accuracy,Post-peak degradation,Worst later degradation,Later rounds hurt > tolerance
0,Linear FLoRA,Dolly,Heter,1,2,27.64,8,28.37,10,27.14,1.23,1.23,True
1,Linear FLoRA,Dolly,Heter,2,1,29.38,5,29.96,10,28.83,1.12,2.32,True
2,Linear FLoRA,Dolly,Heter,3,2,29.24,3,29.42,10,27.60,1.82,2.59,True
3,Linear FLoRA,Dolly,Heter,5,1,29.09,2,29.24,10,26.17,3.07,3.10,True
4,Linear FLoRA,Dolly,Homo,1,10,29.86,10,29.86,10,29.86,0.00,0.00,False
5,Linear FLoRA,Dolly,Homo,2,5,30.54,5,30.54,10,29.55,0.98,1.33,True
6,Linear FLoRA,Dolly,Homo,3,2,31.03,2,31.03,10,28.25,2.78,3.44,True
7,Linear FLoRA,Dolly,Homo,5,2,28.85,8,29.60,10,28.20,1.40,2.20,True
8,Linear FLoRA,Dolly stratified,Heter,1,5,28.03,10,28.87,10,28.87,0.00,0.00,False
9,Linear FLoRA,Dolly stratified,Heter,2,3,28.16,8,29.11,10,26.86,2.24,2.42,True
10,Linear FLoRA,Dolly stratified,Heter,3,1,27.57,2,28.07,10,26.23,1.85,1.86,True
11,Linear FLoRA,Dolly stratified,Heter,5,1,28.34,3,28.49,10,25.24,3.25,3.32,True
12,Linear FLoRA,Dolly stratified,Homo,1,4,28.08,5,28.63,10,27.97,0.67,1.95,True
13,Linear FLoRA,Dolly stratified,Homo,2,2,28.50,9,28.77,10,28.17,0.61,0.61,False
14,Linear FLoRA,Dolly stratified,Homo,3,2,28.85,8,29.17,10,28.04,1.12,1.12,True
15,Linear FLoRA,Dolly stratified,Homo,5,4,29.61,4,29.61,10,28.64,0.98,2.56,True
16,Linear FLoRA,Wizard,Heter,1,1,42.10,2,42.15,10,40.19,1.97,2.19,True
17,Linear FLoRA,Wizard,Heter,2,1,44.27,5,44.68,10,42.18,2.51,2.51,True
18,Linear FLoRA,Wizard,Heter,3,1,46.22,1,46.22,10,38.33,7.88,10.23,True
19,Linear FLoRA,Wizard,Heter,5,1,46.06,1,46.06,10,30.44,15.62,15.62,True
20,Linear FLoRA,Wizard,Homo,1,1,45.10,1,45.10,10,35.58,9.52,9.81,True
21,Linear FLoRA,Wizard,Homo,2,3,43.32,5,43.33,10,39.20,4.14,4.14,True
22,Linear FLoRA,Wizard,Homo,3,1,36.82,2,37.65,10,36.09,1.56,2.68,True
23,Linear FLoRA,Wizard,Homo,5,1,40.23,1,40.23,10,34.61,5.62,5.78,True
24,Linear FLoRA,Wizard stratified,Heter,1,2,44.55,2,44.55,10,39.54,5.02,6.09,True
25,Linear FLoRA,Wizard stratified,Heter,2,1,43.18,7,43.20,10,42.36,0.84,1.31,True
26,Linear FLoRA,Wizard stratified,Heter,3,1,45.74,1,45.74,10,35.82,9.92,9.92,True
27,Linear FLoRA,Wizard stratified,Heter,5,1,42.25,1,42.25,10,32.00,10.26,10.41,True
28,Linear FLoRA,Wizard stratified,Homo,1,1,46.74,1,46.74,10,35.34,11.40,12.72,True
29,Linear FLoRA,Wizard stratified,Homo,2,1,42.06,1,42.06,10,38.94,3.12,3.96,True
30,Linear FLoRA,Wizard stratified,Homo,3,1,38.97,2,38.97,10,34.91,4.05,4.05,True
31,Linear FLoRA,Wizard stratified,Homo,5,1,41.04,1,41.04,10,32.04,9.01,9.01,True

Linear FLoRA: marginal round-gain summary

,Method,Dataset label,Setting,Local epochs,Mean marginal gain,Last marginal gain,Negative marginal rounds
0,Linear FLoRA,Dolly,Heter,1,0.31,-0.81,5
1,Linear FLoRA,Dolly,Heter,2,-0.06,1.20,4
2,Linear FLoRA,Dolly,Heter,3,-0.09,-0.52,5
3,Linear FLoRA,Dolly,Heter,5,-0.32,-1.11,4
4,Linear FLoRA,Dolly,Homo,1,1.32,1.61,4
5,Linear FLoRA,Dolly,Homo,2,0.17,0.05,3
6,Linear FLoRA,Dolly,Homo,3,0.19,-0.25,5
7,Linear FLoRA,Dolly,Homo,5,0.09,0.80,4
8,Linear FLoRA,Dolly stratified,Heter,1,0.80,2.03,4
9,Linear FLoRA,Dolly stratified,Heter,2,-0.00,0.17,3
10,Linear FLoRA,Dolly stratified,Heter,3,-0.15,0.01,5
11,Linear FLoRA,Dolly stratified,Heter,5,-0.34,-0.41,5
12,Linear FLoRA,Dolly stratified,Homo,1,1.10,0.07,3
13,Linear FLoRA,Dolly stratified,Homo,2,0.17,-0.61,5
14,Linear FLoRA,Dolly stratified,Homo,3,0.13,-0.80,4
15,Linear FLoRA,Dolly stratified,Homo,5,0.01,0.10,5
16,Linear FLoRA,Wizard,Heter,1,-0.21,-0.17,5
17,Linear FLoRA,Wizard,Heter,2,-0.23,-0.56,4
18,Linear FLoRA,Wizard,Heter,3,-0.88,2.34,6
19,Linear FLoRA,Wizard,Heter,5,-1.74,-0.61,7
20,Linear FLoRA,Wizard,Homo,1,-1.06,0.29,8
21,Linear FLoRA,Wizard,Homo,2,-0.34,-0.94,6
22,Linear FLoRA,Wizard,Homo,3,-0.08,1.12,6
23,Linear FLoRA,Wizard,Homo,5,-0.62,-1.40,8
24,Linear FLoRA,Wizard stratified,Heter,1,-0.16,1.07,6
25,Linear FLoRA,Wizard stratified,Heter,2,-0.09,0.47,5
26,Linear FLoRA,Wizard stratified,Heter,3,-1.10,-2.15,6
27,Linear FLoRA,Wizard stratified,Heter,5,-1.14,-0.06,7
28,Linear FLoRA,Wizard stratified,Homo,1,-1.27,1.33,7
29,Linear FLoRA,Wizard stratified,Homo,2,-0.35,0.16,4
30,Linear FLoRA,Wizard stratified,Homo,3,-0.45,-1.93,5
31,Linear FLoRA,Wizard stratified,Homo,5,-1.00,-1.84,6

Nonlinear FLoRA: efficient optimal epoch/round pairs within 1.0 percentage point of best

,Method,Dataset label,Setting,Selected epochs,Selected round,Selected accuracy,Selected compute cost,Selected post-peak degradation,Best epochs,Best round,Best accuracy,Accuracy gap to best,Communication-efficient epochs,Communication-efficient round,Communication-efficient accuracy,Communication-efficient compute cost,Communication-efficient gap to best,Selection matches tuning_selected
0,Nonlinear FLoRA,Dolly,Heter,2,4,30.10,8,1.68,3,3,31.06,0.96,3,3,31.06,9,0.0,True
1,Nonlinear FLoRA,Dolly,Homo,3,3,30.22,9,1.67,3,3,30.22,0.00,3,3,30.22,9,0.0,True
2,Nonlinear FLoRA,Dolly stratified,Heter,3,2,30.10,6,0.39,3,2,30.10,0.00,3,2,30.10,6,0.0,True
3,Nonlinear FLoRA,Dolly stratified,Homo,2,6,29.71,12,2.46,2,6,29.71,0.00,2,6,29.71,12,0.0,True
4,Nonlinear FLoRA,Wizard,Heter,3,1,44.13,3,6.04,3,1,44.13,0.00,3,1,44.13,3,0.0,True
5,Nonlinear FLoRA,Wizard,Homo,2,1,42.02,2,3.78,2,1,42.02,0.00,2,1,42.02,2,0.0,True
6,Nonlinear FLoRA,Wizard stratified,Heter,3,1,45.38,3,8.49,3,1,45.38,0.00,3,1,45.38,3,0.0,True
7,Nonlinear FLoRA,Wizard stratified,Homo,2,3,42.88,6,2.16,2,3,42.88,0.00,2,3,42.88,6,0.0,True

Nonlinear FLoRA: per-epoch plateau and degradation diagnostics

,Method,Dataset label,Setting,Local epochs,Plateau round,Plateau accuracy,Best round,Best accuracy,Final round,Final accuracy,Post-peak degradation,Worst later degradation,Later rounds hurt > tolerance
0,Nonlinear FLoRA,Dolly,Heter,1,9,31.03,9,31.03,10,29.64,1.39,1.39,True
1,Nonlinear FLoRA,Dolly,Heter,2,3,30.01,6,30.80,10,29.12,1.68,1.68,True
2,Nonlinear FLoRA,Dolly,Heter,3,3,31.06,3,31.06,10,28.59,2.47,3.57,True
3,Nonlinear FLoRA,Dolly,Heter,5,1,29.15,1,29.15,10,26.07,3.08,3.28,True
4,Nonlinear FLoRA,Dolly,Homo,1,5,27.33,10,28.32,10,28.32,0.00,0.00,False
5,Nonlinear FLoRA,Dolly,Homo,2,3,28.85,7,29.54,10,29.02,0.53,0.53,False
6,Nonlinear FLoRA,Dolly,Homo,3,3,30.22,3,30.22,10,28.55,1.67,3.20,True
7,Nonlinear FLoRA,Dolly,Homo,5,6,29.01,6,29.01,10,25.92,3.10,3.62,True
8,Nonlinear FLoRA,Dolly stratified,Heter,1,7,29.84,7,29.84,10,29.45,0.39,1.32,True
9,Nonlinear FLoRA,Dolly stratified,Heter,2,3,28.12,4,28.96,10,28.05,0.91,1.89,True
10,Nonlinear FLoRA,Dolly stratified,Heter,3,2,30.10,2,30.10,10,29.71,0.39,3.74,True
11,Nonlinear FLoRA,Dolly stratified,Heter,5,1,28.56,1,28.56,10,26.40,2.15,3.25,True
12,Nonlinear FLoRA,Dolly stratified,Homo,1,4,27.62,10,27.92,10,27.92,0.00,0.00,False
13,Nonlinear FLoRA,Dolly stratified,Homo,2,6,29.71,6,29.71,10,27.25,2.46,3.18,True
14,Nonlinear FLoRA,Dolly stratified,Homo,3,2,28.47,3,28.51,10,27.20,1.31,2.00,True
15,Nonlinear FLoRA,Dolly stratified,Homo,5,1,28.50,1,28.50,10,28.19,0.31,2.28,True
16,Nonlinear FLoRA,Wizard,Heter,1,2,40.64,10,40.75,10,40.75,0.00,0.00,False
17,Nonlinear FLoRA,Wizard,Heter,2,2,43.15,5,43.80,10,41.09,2.71,3.44,True
18,Nonlinear FLoRA,Wizard,Heter,3,1,44.13,1,44.13,10,38.09,6.04,6.41,True
19,Nonlinear FLoRA,Wizard,Heter,5,1,40.94,1,40.94,10,34.30,6.64,7.88,True
20,Nonlinear FLoRA,Wizard,Homo,1,8,41.21,9,41.68,10,41.08,0.59,0.59,False
21,Nonlinear FLoRA,Wizard,Homo,2,1,42.02,1,42.02,10,38.24,3.78,3.78,True
22,Nonlinear FLoRA,Wizard,Homo,3,1,40.57,1,40.57,10,34.67,5.90,5.90,True
23,Nonlinear FLoRA,Wizard,Homo,5,1,37.09,1,37.09,10,33.35,3.73,4.34,True
24,Nonlinear FLoRA,Wizard stratified,Heter,1,2,39.52,9,39.57,10,38.92,0.65,0.65,False
25,Nonlinear FLoRA,Wizard stratified,Heter,2,2,43.75,2,43.75,10,40.84,2.91,2.91,True
26,Nonlinear FLoRA,Wizard stratified,Heter,3,1,45.38,1,45.38,10,36.89,8.49,10.28,True
27,Nonlinear FLoRA,Wizard stratified,Homo,1,10,41.17,10,41.17,10,41.17,0.00,0.00,False
28,Nonlinear FLoRA,Wizard stratified,Homo,2,3,42.88,3,42.88,10,40.72,2.16,2.61,True
29,Nonlinear FLoRA,Wizard stratified,Homo,3,1,41.80,1,41.80,10,34.43,7.37,7.39,True

Nonlinear FLoRA: marginal round-gain summary

,Method,Dataset label,Setting,Local epochs,Mean marginal gain,Last marginal gain,Negative marginal rounds
0,Nonlinear FLoRA,Dolly,Heter,1,0.87,-1.39,3
1,Nonlinear FLoRA,Dolly,Heter,2,0.35,-1.01,5
2,Nonlinear FLoRA,Dolly,Heter,3,0.09,1.09,3
3,Nonlinear FLoRA,Dolly,Heter,5,-0.34,-0.04,6
4,Nonlinear FLoRA,Dolly,Homo,1,1.28,0.17,2
5,Nonlinear FLoRA,Dolly,Homo,2,0.28,-0.49,4
6,Nonlinear FLoRA,Dolly,Homo,3,0.29,0.12,3
7,Nonlinear FLoRA,Dolly,Homo,5,-0.22,0.53,5
8,Nonlinear FLoRA,Dolly stratified,Heter,1,0.79,0.93,4
9,Nonlinear FLoRA,Dolly stratified,Heter,2,0.34,0.98,3
10,Nonlinear FLoRA,Dolly stratified,Heter,3,0.28,1.35,4
11,Nonlinear FLoRA,Dolly stratified,Heter,5,-0.24,0.38,5
12,Nonlinear FLoRA,Dolly stratified,Homo,1,1.22,0.91,3
13,Nonlinear FLoRA,Dolly stratified,Homo,2,0.14,0.72,4
14,Nonlinear FLoRA,Dolly stratified,Homo,3,0.06,-0.59,5
15,Nonlinear FLoRA,Dolly stratified,Homo,5,-0.03,1.22,5
16,Nonlinear FLoRA,Wizard,Heter,1,0.37,0.17,3
17,Nonlinear FLoRA,Wizard,Heter,2,0.38,0.73,5
18,Nonlinear FLoRA,Wizard,Heter,3,-0.67,0.37,7
19,Nonlinear FLoRA,Wizard,Heter,5,-0.74,-0.81,6
20,Nonlinear FLoRA,Wizard,Homo,1,0.45,-0.59,3
21,Nonlinear FLoRA,Wizard,Homo,2,-0.42,-1.62,6
22,Nonlinear FLoRA,Wizard,Homo,3,-0.66,-1.63,5
23,Nonlinear FLoRA,Wizard,Homo,5,-0.41,0.60,7
24,Nonlinear FLoRA,Wizard stratified,Heter,1,0.14,-0.65,4
25,Nonlinear FLoRA,Wizard stratified,Heter,2,0.30,-1.41,6
26,Nonlinear FLoRA,Wizard stratified,Heter,3,-0.94,1.01,5
27,Nonlinear FLoRA,Wizard stratified,Homo,1,0.42,1.67,2
28,Nonlinear FLoRA,Wizard stratified,Homo,2,-0.10,0.26,4
29,Nonlinear FLoRA,Wizard stratified,Homo,3,-0.82,0.03,7

Nonlinear FFA: efficient optimal epoch/round pairs within 1.0 percentage point of best

,Method,Dataset label,Setting,Selected epochs,Selected round,Selected accuracy,Selected compute cost,Selected post-peak degradation,Best epochs,Best round,Best accuracy,Accuracy gap to best,Communication-efficient epochs,Communication-efficient round,Communication-efficient accuracy,Communication-efficient compute cost,Communication-efficient gap to best,Selection matches tuning_selected
0,Nonlinear FFA,Dolly,Heter,3,4,28.52,12,1.59,5,9,29.05,0.52,3,4,28.52,12,0.52,True
1,Nonlinear FFA,Dolly,Homo,2,3,29.90,6,0.77,5,7,30.87,0.97,2,3,29.90,6,0.97,True
2,Nonlinear FFA,Dolly stratified,Heter,3,5,29.62,15,1.67,3,5,29.62,0.00,3,5,29.62,15,0.00,True
3,Nonlinear FFA,Dolly stratified,Homo,3,7,30.62,21,0.00,3,10,31.26,0.65,3,7,30.62,21,0.65,True
4,Nonlinear FFA,Wizard,Heter,1,6,33.19,6,0.00,1,10,33.63,0.44,5,2,33.12,10,0.51,True
5,Nonlinear FFA,Wizard,Homo,2,1,30.69,2,0.16,5,4,31.55,0.86,2,1,30.69,2,0.86,True
6,Nonlinear FFA,Wizard stratified,Heter,2,3,32.46,6,1.79,5,3,33.37,0.91,2,3,32.46,6,0.91,True
7,Nonlinear FFA,Wizard stratified,Homo,2,2,31.81,4,1.36,5,1,32.35,0.54,5,1,32.35,5,0.00,True

Nonlinear FFA: per-epoch plateau and degradation diagnostics

,Method,Dataset label,Setting,Local epochs,Plateau round,Plateau accuracy,Best round,Best accuracy,Final round,Final accuracy,Post-peak degradation,Worst later degradation,Later rounds hurt > tolerance
0,Nonlinear FFA,Dolly,Heter,1,8,26.33,10,27.24,10,27.24,0.00,0.00,False
1,Nonlinear FFA,Dolly,Heter,2,7,27.52,9,28.38,10,27.90,0.48,0.48,False
2,Nonlinear FFA,Dolly,Heter,3,4,28.52,6,28.99,10,27.40,1.59,2.96,True
3,Nonlinear FFA,Dolly,Heter,5,4,28.88,9,29.05,10,26.78,2.26,2.26,True
4,Nonlinear FFA,Dolly,Homo,1,6,29.29,6,29.29,10,28.81,0.48,1.64,True
5,Nonlinear FFA,Dolly,Homo,2,3,29.90,9,30.31,10,29.55,0.77,0.77,False
6,Nonlinear FFA,Dolly,Homo,3,4,29.32,7,29.56,10,29.45,0.11,0.49,False
7,Nonlinear FFA,Dolly,Homo,5,5,30.35,7,30.87,10,29.19,1.68,1.91,True
8,Nonlinear FFA,Dolly stratified,Heter,1,6,25.59,9,26.40,10,26.28,0.12,0.12,False
9,Nonlinear FFA,Dolly stratified,Heter,2,5,27.69,9,28.42,10,25.92,2.50,2.50,True
10,Nonlinear FFA,Dolly stratified,Heter,3,5,29.62,5,29.62,10,27.94,1.67,1.69,True
11,Nonlinear FFA,Dolly stratified,Heter,5,5,29.46,5,29.46,10,28.90,0.56,2.10,True
12,Nonlinear FFA,Dolly stratified,Homo,1,6,27.63,8,28.55,10,27.68,0.87,0.87,False
13,Nonlinear FFA,Dolly stratified,Homo,2,4,29.31,10,29.76,10,29.76,0.00,0.00,False
14,Nonlinear FFA,Dolly stratified,Homo,3,7,30.62,10,31.26,10,31.26,0.00,0.00,False
15,Nonlinear FFA,Dolly stratified,Homo,5,8,30.71,9,30.97,10,28.46,2.51,2.51,True
16,Nonlinear FFA,Wizard,Heter,1,6,33.19,10,33.63,10,33.63,0.00,0.00,False
17,Nonlinear FFA,Wizard,Heter,2,4,33.03,4,33.03,10,31.37,1.67,1.76,True
18,Nonlinear FFA,Wizard,Heter,3,2,32.20,4,32.49,10,31.01,1.48,1.56,True
19,Nonlinear FFA,Wizard,Heter,5,2,33.12,7,33.56,10,31.51,2.05,2.05,True
20,Nonlinear FFA,Wizard,Homo,1,2,30.87,4,31.50,10,29.85,1.65,1.77,True
21,Nonlinear FFA,Wizard,Homo,2,1,30.69,4,31.31,10,31.15,0.16,2.22,True
22,Nonlinear FFA,Wizard,Homo,3,2,31.42,2,31.42,10,30.57,0.85,2.61,True
23,Nonlinear FFA,Wizard,Homo,5,2,30.67,4,31.55,10,27.80,3.74,3.74,True
24,Nonlinear FFA,Wizard stratified,Heter,1,5,32.34,8,33.07,10,31.33,1.74,1.74,True
25,Nonlinear FFA,Wizard stratified,Heter,2,3,32.46,4,32.85,10,31.06,1.79,2.00,True
26,Nonlinear FFA,Wizard stratified,Heter,3,5,32.75,5,32.75,10,32.29,0.46,1.08,True
27,Nonlinear FFA,Wizard stratified,Heter,5,3,33.37,3,33.37,10,30.34,3.03,3.03,True
28,Nonlinear FFA,Wizard stratified,Homo,1,2,31.25,4,31.29,10,29.61,1.69,1.69,True
29,Nonlinear FFA,Wizard stratified,Homo,2,2,31.81,5,31.84,10,30.48,1.36,2.62,True
30,Nonlinear FFA,Wizard stratified,Homo,3,1,30.92,6,31.85,10,30.55,1.30,2.00,True
31,Nonlinear FFA,Wizard stratified,Homo,5,1,32.35,1,32.35,10,28.58,3.77,4.57,True

Nonlinear FFA: marginal round-gain summary

,Method,Dataset label,Setting,Local epochs,Mean marginal gain,Last marginal gain,Negative marginal rounds
0,Nonlinear FFA,Dolly,Heter,1,0.88,0.65,2
1,Nonlinear FFA,Dolly,Heter,2,0.76,-0.48,4
2,Nonlinear FFA,Dolly,Heter,3,0.40,-1.16,5
3,Nonlinear FFA,Dolly,Heter,5,0.05,-2.26,5
4,Nonlinear FFA,Dolly,Homo,1,1.39,0.31,2
5,Nonlinear FFA,Dolly,Homo,2,1.35,-0.77,5
6,Nonlinear FFA,Dolly,Homo,3,1.08,0.38,4
7,Nonlinear FFA,Dolly,Homo,5,0.54,0.23,4
8,Nonlinear FFA,Dolly stratified,Heter,1,0.88,-0.12,2
9,Nonlinear FFA,Dolly stratified,Heter,2,0.72,-2.50,3
10,Nonlinear FFA,Dolly stratified,Heter,3,0.51,-0.66,4
11,Nonlinear FFA,Dolly stratified,Heter,5,0.42,-0.07,3
12,Nonlinear FFA,Dolly stratified,Homo,1,1.31,-0.66,2
13,Nonlinear FFA,Dolly stratified,Homo,2,1.25,0.22,2
14,Nonlinear FFA,Dolly stratified,Homo,3,1.31,1.48,3
15,Nonlinear FFA,Dolly stratified,Homo,5,0.27,-2.51,3
16,Nonlinear FFA,Wizard,Heter,1,0.71,1.62,2
17,Nonlinear FFA,Wizard,Heter,2,0.26,-0.06,5
18,Nonlinear FFA,Wizard,Heter,3,0.20,-0.50,4
19,Nonlinear FFA,Wizard,Heter,5,0.07,-0.70,6
20,Nonlinear FFA,Wizard,Homo,1,0.20,0.11,3
21,Nonlinear FFA,Wizard,Homo,2,0.05,1.50,4
22,Nonlinear FFA,Wizard,Homo,3,0.08,1.28,3
23,Nonlinear FFA,Wizard,Homo,5,-0.29,-2.00,6
24,Nonlinear FFA,Wizard stratified,Heter,1,0.48,-0.26,4
25,Nonlinear FFA,Wizard stratified,Heter,2,0.25,0.17,3
26,Nonlinear FFA,Wizard stratified,Heter,3,0.32,0.07,3
27,Nonlinear FFA,Wizard stratified,Heter,5,0.00,-2.10,4
28,Nonlinear FFA,Wizard stratified,Homo,1,0.25,-0.06,5
29,Nonlinear FFA,Wizard stratified,Homo,2,0.06,-1.07,4
30,Nonlinear FFA,Wizard stratified,Homo,3,-0.04,-0.01,5
31,Nonlinear FFA,Wizard stratified,Homo,5,-0.42,-0.14,5

All complete-run methods: reusable optimal-pair table

,Method,Dataset label,Setting,Selected epochs,Selected round,Selected accuracy,Selected compute cost,Selected post-peak degradation,Best epochs,Best round,Best accuracy,Accuracy gap to best,Communication-efficient epochs,Communication-efficient round,Communication-efficient accuracy,Communication-efficient compute cost,Communication-efficient gap to best,Selection matches tuning_selected
0,Linear FLoRA,Dolly,Heter,2,1,29.38,2,1.12,2,5,29.96,0.58,2,1,29.38,2,0.58,True
1,Nonlinear FFA,Dolly,Heter,3,4,28.52,12,1.59,5,9,29.05,0.52,3,4,28.52,12,0.52,True
2,Nonlinear FLoRA,Dolly,Heter,2,4,30.10,8,1.68,3,3,31.06,0.96,3,3,31.06,9,0.00,True
3,Linear FLoRA,Dolly,Homo,3,2,31.03,6,2.78,3,2,31.03,0.00,3,2,31.03,6,0.00,True
4,Nonlinear FFA,Dolly,Homo,2,3,29.90,6,0.77,5,7,30.87,0.97,2,3,29.90,6,0.97,True
5,Nonlinear FLoRA,Dolly,Homo,3,3,30.22,9,1.67,3,3,30.22,0.00,3,3,30.22,9,0.00,True
6,Linear FLoRA,Dolly stratified,Heter,5,1,28.34,5,3.25,2,8,29.11,0.77,5,1,28.34,5,0.77,True
7,Nonlinear FFA,Dolly stratified,Heter,3,5,29.62,15,1.67,3,5,29.62,0.00,3,5,29.62,15,0.00,True
8,Nonlinear FLoRA,Dolly stratified,Heter,3,2,30.10,6,0.39,3,2,30.10,0.00,3,2,30.10,6,0.00,True
9,Linear FLoRA,Dolly stratified,Homo,1,5,28.63,5,0.67,5,4,29.61,0.98,3,2,28.85,6,0.77,True
10,Nonlinear FFA,Dolly stratified,Homo,3,7,30.62,21,0.00,3,10,31.26,0.65,3,7,30.62,21,0.65,True
11,Nonlinear FLoRA,Dolly stratified,Homo,2,6,29.71,12,2.46,2,6,29.71,0.00,2,6,29.71,12,0.00,True
12,Linear FLoRA,Wizard,Heter,3,1,46.22,3,7.88,3,1,46.22,0.00,3,1,46.22,3,0.00,True
13,Nonlinear FFA,Wizard,Heter,1,6,33.19,6,0.00,1,10,33.63,0.44,5,2,33.12,10,0.51,True
14,Nonlinear FLoRA,Wizard,Heter,3,1,44.13,3,6.04,3,1,44.13,0.00,3,1,44.13,3,0.00,True
15,Linear FLoRA,Wizard,Homo,1,1,45.10,1,9.52,1,1,45.10,0.00,1,1,45.10,1,0.00,True
16,Nonlinear FFA,Wizard,Homo,2,1,30.69,2,0.16,5,4,31.55,0.86,2,1,30.69,2,0.86,True
17,Nonlinear FLoRA,Wizard,Homo,2,1,42.02,2,3.78,2,1,42.02,0.00,2,1,42.02,2,0.00,True
18,Linear FLoRA,Wizard stratified,Heter,3,1,45.74,3,9.92,3,1,45.74,0.00,3,1,45.74,3,0.00,True
19,Nonlinear FFA,Wizard stratified,Heter,2,3,32.46,6,1.79,5,3,33.37,0.91,2,3,32.46,6,0.91,True
20,Nonlinear FLoRA,Wizard stratified,Heter,3,1,45.38,3,8.49,3,1,45.38,0.00,3,1,45.38,3,0.00,True
21,Linear FLoRA,Wizard stratified,Homo,1,1,46.74,1,11.40,1,1,46.74,0.00,1,1,46.74,1,0.00,True
22,Nonlinear FFA,Wizard stratified,Homo,2,2,31.81,4,1.36,5,1,32.35,0.54,5,1,32.35,5,0.00,True
23,Nonlinear FLoRA,Wizard stratified,Homo,2,3,42.88,6,2.16,2,3,42.88,0.00,2,3,42.88,6,0.00,True

## Method Alignment

In [36]:
def _winner_table(frame, value_column, epoch_column, round_column, accuracy_label, cost_column=None):
    if frame.empty:
        return pd.DataFrame()
    index_columns = ['Dataset label', 'Model', 'Setting']
    ordered = frame.sort_values(value_column, ascending=False)
    winners = ordered.groupby(index_columns, as_index=False).first()
    columns = index_columns + ['Method', epoch_column, round_column, value_column]
    rename_map = {
        epoch_column: 'Epochs',
        round_column: 'Round',
        value_column: accuracy_label,
    }
    if cost_column and cost_column in winners.columns:
        columns.append(cost_column)
        rename_map[cost_column] = 'Compute cost'
    return winners[columns].rename(columns=rename_map)


def build_budget_recommendations(summary):
    if summary.empty:
        return pd.DataFrame()
    budgets = [
        ('Low compute', 3),
        ('Medium compute', 10),
        ('High compute', None),
    ]
    rows = []
    group_columns = ['Dataset label', 'Model', 'Setting']
    for group_values, group in summary.groupby(group_columns, sort=False):
        for budget_rank, (budget_label, max_compute_cost) in enumerate(budgets):
            eligible = group if max_compute_cost is None else group[group['Compute cost'] <= max_compute_cost]
            if eligible.empty:
                continue
            best = eligible.loc[eligible['Mean accuracy'].idxmax()]
            rows.append(
                dict(zip(group_columns, group_values))
                | {
                    'Budget rank': budget_rank,
                    'Budget': budget_label,
                    'Max compute cost': 'unbounded' if max_compute_cost is None else max_compute_cost,
                    'Method': best['Method'],
                    'Local epochs': int(best['Local epochs']),
                    'Round': int(best['Round']),
                    'Accuracy': float(best['Mean accuracy']),
                    'Compute cost': int(best['Compute cost']),
                }
            )
    return (
        pd.DataFrame(rows)
        .sort_values(['Dataset label', 'Setting', 'Budget rank'])
        .drop(columns=['Budget rank'])
    )


if tuning_selected.empty:
    print('No selected configurations yet.')
else:
    index_columns = ['Dataset label', 'Model', 'Setting']
    alignment = tuning_selected.pivot(
        index=index_columns,
        columns='Method',
        values=['Selected epochs', 'Selected round', 'Selected accuracy', 'Best epochs', 'Best round', 'Best accuracy'],
    )
    display(alignment.round(2))

    absolute_winners = _winner_table(
        optimal_epoch_round_pairs,
        'Best accuracy',
        'Best epochs',
        'Best round',
        'Best accuracy',
        cost_column='Best compute cost',
    )
    compute_efficient_winners = _winner_table(
        optimal_epoch_round_pairs,
        'Selected accuracy',
        'Selected epochs',
        'Selected round',
        'Compute-efficient accuracy',
        cost_column='Selected compute cost',
    )
    communication_efficient_winners = _winner_table(
        optimal_epoch_round_pairs,
        'Communication-efficient accuracy',
        'Communication-efficient epochs',
        'Communication-efficient round',
        'Communication-efficient accuracy',
        cost_column='Communication-efficient compute cost',
    )
    budget_recommendations = build_budget_recommendations(tuning_summary)

    print('Absolute-best method by dataset/setting')
    display(absolute_winners.round(2))
    print('Compute-efficient near-best method by dataset/setting')
    display(compute_efficient_winners.round(2))
    print('Communication-efficient near-best method by dataset/setting')
    display(communication_efficient_winners.round(2))
    print('Budget-regime recommendations from complete runs')
    display(budget_recommendations.round(2))

    absolute_winners.to_csv(OUTPUT_DIR / 'method_winners_absolute.csv', index=False)
    compute_efficient_winners.to_csv(OUTPUT_DIR / 'method_winners_compute_efficient.csv', index=False)
    communication_efficient_winners.to_csv(OUTPUT_DIR / 'method_winners_communication_efficient.csv', index=False)
    budget_recommendations.to_csv(OUTPUT_DIR / 'method_budget_recommendations.csv', index=False)

                                    Selected epochs                \
Method                                 Linear FLoRA Nonlinear FFA
Dataset label     Model     Setting
Dolly             TinyLlama Heter               2.0           3.0
                            Homo                3.0           2.0
Dolly stratified  TinyLlama Heter               5.0           3.0
                            Homo                1.0           3.0
Wizard            TinyLlama Heter               3.0           1.0
                            Homo                1.0           2.0
Wizard stratified TinyLlama Heter               3.0           2.0
                            Homo                1.0           2.0

                                                    Selected round  \
Method                              Nonlinear FLoRA   Linear FLoRA
Dataset label     Model     Setting
Dolly             TinyLlama Heter               2.0            1.0
                            Homo                3.0            2.0
Dolly stratified  TinyLlama Heter               3.0            1.0
                            Homo                2.0            5.0
Wizard            TinyLlama Heter               3.0            1.0
                            Homo                2.0            1.0
Wizard stratified TinyLlama Heter               3.0            1.0
                            Homo                2.0            1.0

                                                                   \
Method                              Nonlinear FFA Nonlinear FLoRA
Dataset label     Model     Setting
Dolly             TinyLlama Heter             4.0             4.0
                            Homo              3.0             3.0
Dolly stratified  TinyLlama Heter             5.0             2.0
                            Homo              7.0             6.0
Wizard            TinyLlama Heter             6.0             1.0
                            Homo              1.0             1.0
Wizard stratified TinyLlama Heter             3.0             1.0
                            Homo              2.0             3.0

                                    Selected accuracy                \
Method                                   Linear FLoRA Nonlinear FFA
Dataset label     Model     Setting
Dolly             TinyLlama Heter               29.38         28.52
                            Homo                31.03         29.90
Dolly stratified  TinyLlama Heter               28.34         29.62
                            Homo                28.63         30.62
Wizard            TinyLlama Heter               46.22         33.19
                            Homo                45.10         30.69
Wizard stratified TinyLlama Heter               45.74         32.46
                            Homo                46.74         31.81

                                                     Best epochs  \
Method                              Nonlinear FLoRA Linear FLoRA
Dataset label     Model     Setting
Dolly             TinyLlama Heter             30.10          2.0
                            Homo              30.22          3.0
Dolly stratified  TinyLlama Heter             30.10          2.0
                            Homo              29.71          5.0
Wizard            TinyLlama Heter             44.13          3.0
                            Homo              42.02          1.0
Wizard stratified TinyLlama Heter             45.38          3.0
                            Homo              42.88          1.0

                                                                   \
Method                              Nonlinear FFA Nonlinear FLoRA
Dataset label     Model     Setting
Dolly             TinyLlama Heter             5.0             3.0
                            Homo              5.0             3.0
Dolly stratified  TinyLlama Heter             3.0             3.0
                            Homo              3.0             2.0
Wizard            TinyLlama Heter             1.0             3.0
                            Homo              5.0             2.0
Wizard stratified TinyLlama Heter             5.0             3.0
                            Homo              5.0             2.0

                                      Best round                \
Method                              Linear FLoRA Nonlinear FFA
Dataset label     Model     Setting
Dolly             TinyLlama Heter            5.0           9.0
                            Homo             2.0           7.0
Dolly stratified  TinyLlama Heter            8.0           5.0
                            Homo             4.0          10.0
Wizard            TinyLlama Heter            1.0          10.0
                            Homo             1.0           4.0
Wizard stratified TinyLlama Heter            1.0           3.0
                            Homo             1.0           1.0

                                                    Best accuracy  \
Method                              Nonlinear FLoRA  Linear FLoRA
Dataset label     Model     Setting
Dolly             TinyLlama Heter               3.0         29.96
                            Homo                3.0         31.03
Dolly stratified  TinyLlama Heter               2.0         29.11
                            Homo                6.0         29.61
Wizard            TinyLlama Heter               1.0         46.22
                            Homo                1.0         45.10
Wizard stratified TinyLlama Heter               1.0         45.74
                            Homo                3.0         46.74


Method                              Nonlinear FFA Nonlinear FLoRA
Dataset label     Model     Setting
Dolly             TinyLlama Heter           29.05           31.06
                            Homo            30.87           30.22
Dolly stratified  TinyLlama Heter           29.62           30.10
                            Homo            31.26           29.71
Wizard            TinyLlama Heter           33.63           44.13
                            Homo            31.55           42.02
Wizard stratified TinyLlama Heter           33.37           45.38
                            Homo            32.35           42.88

Absolute-best method by dataset/setting

,Dataset label,Model,Setting,Method,Epochs,Round,Best accuracy,Compute cost
0,Dolly,TinyLlama,Heter,Nonlinear FLoRA,3,3,31.06,9
1,Dolly,TinyLlama,Homo,Linear FLoRA,3,2,31.03,6
2,Dolly stratified,TinyLlama,Heter,Nonlinear FLoRA,3,2,30.10,6
3,Dolly stratified,TinyLlama,Homo,Nonlinear FFA,3,10,31.26,30
4,Wizard,TinyLlama,Heter,Linear FLoRA,3,1,46.22,3
5,Wizard,TinyLlama,Homo,Linear FLoRA,1,1,45.10,1
6,Wizard stratified,TinyLlama,Heter,Linear FLoRA,3,1,45.74,3
7,Wizard stratified,TinyLlama,Homo,Linear FLoRA,1,1,46.74,1

Compute-efficient near-best method by dataset/setting

,Dataset label,Model,Setting,Method,Epochs,Round,Compute-efficient accuracy,Compute cost
0,Dolly,TinyLlama,Heter,Nonlinear FLoRA,2,4,30.10,8
1,Dolly,TinyLlama,Homo,Linear FLoRA,3,2,31.03,6
2,Dolly stratified,TinyLlama,Heter,Nonlinear FLoRA,3,2,30.10,6
3,Dolly stratified,TinyLlama,Homo,Nonlinear FFA,3,7,30.62,21
4,Wizard,TinyLlama,Heter,Linear FLoRA,3,1,46.22,3
5,Wizard,TinyLlama,Homo,Linear FLoRA,1,1,45.10,1
6,Wizard stratified,TinyLlama,Heter,Linear FLoRA,3,1,45.74,3
7,Wizard stratified,TinyLlama,Homo,Linear FLoRA,1,1,46.74,1

Communication-efficient near-best method by dataset/setting

,Dataset label,Model,Setting,Method,Epochs,Round,Communication-efficient accuracy,Compute cost
0,Dolly,TinyLlama,Heter,Nonlinear FLoRA,3,3,31.06,9
1,Dolly,TinyLlama,Homo,Linear FLoRA,3,2,31.03,6
2,Dolly stratified,TinyLlama,Heter,Nonlinear FLoRA,3,2,30.10,6
3,Dolly stratified,TinyLlama,Homo,Nonlinear FFA,3,7,30.62,21
4,Wizard,TinyLlama,Heter,Linear FLoRA,3,1,46.22,3
5,Wizard,TinyLlama,Homo,Linear FLoRA,1,1,45.10,1
6,Wizard stratified,TinyLlama,Heter,Linear FLoRA,3,1,45.74,3
7,Wizard stratified,TinyLlama,Homo,Linear FLoRA,1,1,46.74,1

Budget-regime recommendations from complete runs

,Dataset label,Model,Setting,Budget,Max compute cost,Method,Local epochs,Round,Accuracy,Compute cost
0,Dolly,TinyLlama,Heter,Low compute,3,Linear FLoRA,2,1,29.38,2
1,Dolly,TinyLlama,Heter,Medium compute,10,Nonlinear FLoRA,3,3,31.06,9
2,Dolly,TinyLlama,Heter,High compute,unbounded,Nonlinear FLoRA,3,3,31.06,9
3,Dolly,TinyLlama,Homo,Low compute,3,Linear FLoRA,2,1,27.98,2
4,Dolly,TinyLlama,Homo,Medium compute,10,Linear FLoRA,3,2,31.03,6
5,Dolly,TinyLlama,Homo,High compute,unbounded,Linear FLoRA,3,2,31.03,6
6,Dolly stratified,TinyLlama,Heter,Low compute,3,Nonlinear FLoRA,1,3,28.49,3
7,Dolly stratified,TinyLlama,Heter,Medium compute,10,Nonlinear FLoRA,3,2,30.10,6
8,Dolly stratified,TinyLlama,Heter,High compute,unbounded,Nonlinear FLoRA,3,2,30.10,6
9,Dolly stratified,TinyLlama,Homo,Low compute,3,Linear FLoRA,1,2,27.59,2
10,Dolly stratified,TinyLlama,Homo,Medium compute,10,Nonlinear FFA,2,4,29.31,8
11,Dolly stratified,TinyLlama,Homo,High compute,unbounded,Nonlinear FFA,3,10,31.26,30
12,Wizard,TinyLlama,Heter,Low compute,3,Linear FLoRA,3,1,46.22,3
13,Wizard,TinyLlama,Heter,Medium compute,10,Linear FLoRA,3,1,46.22,3
14,Wizard,TinyLlama,Heter,High compute,unbounded,Linear FLoRA,3,1,46.22,3
15,Wizard,TinyLlama,Homo,Low compute,3,Linear FLoRA,1,1,45.10,1
16,Wizard,TinyLlama,Homo,Medium compute,10,Linear FLoRA,1,1,45.10,1
17,Wizard,TinyLlama,Homo,High compute,unbounded,Linear FLoRA,1,1,45.10,1
18,Wizard stratified,TinyLlama,Heter,Low compute,3,Linear FLoRA,3,1,45.74,3
19,Wizard stratified,TinyLlama,Heter,Medium compute,10,Linear FLoRA,3,1,45.74,3
20,Wizard stratified,TinyLlama,Heter,High compute,unbounded,Linear FLoRA,3,1,45.74,3
21,Wizard stratified,TinyLlama,Homo,Low compute,3,Linear FLoRA,1,1,46.74,1
22,Wizard stratified,TinyLlama,Homo,Medium compute,10,Linear FLoRA,1,1,46.74,1
23,Wizard stratified,TinyLlama,Homo,High compute,unbounded,Linear FLoRA,1,1,46.74,1

## Dynamic Epoch Oracle

This post-hoc view asks which fixed local-epoch curve is best at each communication round. It is an oracle envelope over separate fixed-epoch runs, not evidence that changing epochs mid-training will exactly reproduce the same path. To avoid over-interpreting noise, a smoothed schedule only switches epoch counts when the best available epoch improves accuracy by at least `SWITCH_GAIN_THRESHOLD` percentage points over keeping the previous epoch count.

In [37]:
def build_dynamic_epoch_oracle(summary, switch_gain_threshold=0.5):
    if summary.empty:
        return pd.DataFrame(), pd.DataFrame()

    case_columns = ['Method key', 'Method', 'Dataset', 'Dataset label', 'Model key', 'Model', 'Setting key', 'Setting']
    rows = []
    for case_values, group in summary.groupby(case_columns, sort=False):
        case_base = dict(zip(case_columns, case_values))
        current_epoch = None
        previous_smoothed_epoch = None
        for round_value, round_group in group.sort_values(['Round', 'Local epochs']).groupby('Round', sort=True):
            candidates = round_group.sort_values(['Mean accuracy', 'Local epochs'], ascending=[False, True])
            oracle = candidates.iloc[0]
            oracle_epoch = int(oracle['Local epochs'])
            oracle_accuracy = float(oracle['Mean accuracy'])

            if current_epoch is None:
                chosen = oracle
                smoothed_epoch = oracle_epoch
                smoothed_accuracy = oracle_accuracy
                gain_over_current = 0.0
                meaningful_switch = False
            else:
                current_rows = round_group[round_group['Local epochs'].astype(int) == int(current_epoch)]
                current_candidate = current_rows.iloc[0] if not current_rows.empty else oracle
                current_accuracy = float(current_candidate['Mean accuracy'])
                gain_over_current = oracle_accuracy - current_accuracy
                should_switch = oracle_epoch != int(current_epoch) and gain_over_current >= switch_gain_threshold
                chosen = oracle if should_switch else current_candidate
                smoothed_epoch = int(chosen['Local epochs'])
                smoothed_accuracy = float(chosen['Mean accuracy'])
                meaningful_switch = previous_smoothed_epoch is not None and smoothed_epoch != int(previous_smoothed_epoch)

            current_epoch = smoothed_epoch
            previous_smoothed_epoch = smoothed_epoch
            rows.append(
                case_base
                | {
                    'Round': int(round_value),
                    'Oracle epochs': oracle_epoch,
                    'Oracle accuracy': oracle_accuracy,
                    'Smoothed epochs': smoothed_epoch,
                    'Smoothed accuracy': smoothed_accuracy,
                    'Oracle gain over current epoch': float(gain_over_current),
                    'Meaningful switch': bool(meaningful_switch),
                    'Switch threshold': float(switch_gain_threshold),
                    'Compute cost': int(smoothed_epoch) * int(round_value),
                }
            )

    oracle_frame = pd.DataFrame(rows).sort_values(case_columns + ['Round'])
    schedule_rows = []
    for case_values, group in oracle_frame.groupby(case_columns, sort=False):
        case_base = dict(zip(case_columns, case_values))
        curve = group.sort_values('Round')
        segments = []
        segment_start = int(curve.iloc[0]['Round'])
        segment_epoch = int(curve.iloc[0]['Smoothed epochs'])
        previous_round = segment_start
        for _, row in curve.iloc[1:].iterrows():
            round_value = int(row['Round'])
            epoch_value = int(row['Smoothed epochs'])
            if epoch_value != segment_epoch:
                end_text = str(previous_round) if previous_round == segment_start else f'{segment_start}-{previous_round}'
                segments.append(f'r{end_text}: e{segment_epoch}')
                segment_start = round_value
                segment_epoch = epoch_value
            previous_round = round_value
        end_text = str(previous_round) if previous_round == segment_start else f'{segment_start}-{previous_round}'
        segments.append(f'r{end_text}: e{segment_epoch}')

        first_epoch = int(curve.iloc[0]['Smoothed epochs'])
        final_epoch = int(curve.iloc[-1]['Smoothed epochs'])
        switch_count = int(curve['Meaningful switch'].sum())
        if switch_count == 0:
            follow_up = f'Keep e{first_epoch}; test early stopping around the best/plateau round.'
        elif first_epoch > final_epoch:
            follow_up = 'Test high-local-epoch warmup followed by lower local epochs.'
        elif first_epoch < final_epoch:
            follow_up = 'Test lower-epoch warmup followed by higher local epochs.'
        else:
            follow_up = 'Test a staged schedule; switches may reflect round-specific instability.'

        schedule_rows.append(
            case_base
            | {
                'Smoothed schedule': '; '.join(segments),
                'Meaningful switches': switch_count,
                'First smoothed epochs': first_epoch,
                'Final smoothed epochs': final_epoch,
                'Max oracle accuracy': float(curve['Oracle accuracy'].max()),
                'Max smoothed accuracy': float(curve['Smoothed accuracy'].max()),
                'Follow-up experiment suggestion': follow_up,
            }
        )

    schedule_frame = pd.DataFrame(schedule_rows).sort_values(['Dataset label', 'Setting', 'Method'])
    return oracle_frame, schedule_frame


def _dynamic_slug(value):
    return str(value).lower().replace(' ', '_').replace('-', '_').replace('/', '_')


def _write_dynamic_plot(fig, output_stem, png_warnings):
    output_stem.parent.mkdir(parents=True, exist_ok=True)
    fig.write_html(output_stem.with_suffix('.html'), include_plotlyjs='cdn')
    png_path = output_stem.with_suffix('.png')
    try:
        fig.write_image(png_path, scale=2)
    except Exception as exc:
        message = str(exc).strip() or type(exc).__name__
        png_warnings.append(message.splitlines()[0])
        png_path = None
    return png_path


dynamic_epoch_oracle, dynamic_epoch_schedule = build_dynamic_epoch_oracle(
    tuning_summary,
    switch_gain_threshold=SWITCH_GAIN_THRESHOLD,
)

dynamic_epoch_oracle.to_csv(OUTPUT_DIR / 'dynamic_epoch_oracle.csv', index=False)
dynamic_epoch_schedule.to_csv(OUTPUT_DIR / 'dynamic_epoch_schedule.csv', index=False)

if dynamic_epoch_schedule.empty:
    print('No dynamic epoch schedule data available.')
else:
    display(
        dynamic_epoch_schedule[
            [
                'Method',
                'Dataset label',
                'Setting',
                'Smoothed schedule',
                'Meaningful switches',
                'Max smoothed accuracy',
                'Follow-up experiment suggestion',
            ]
        ].round(2)
    )

    dynamic_png_warnings = []
    saved_dynamic_png = []
    for dataset, dataset_data in dynamic_epoch_oracle.groupby('Dataset', sort=False):
        dataset_label = dataset_data['Dataset label'].iloc[0]
        fig_accuracy = px.line(
            dataset_data,
            x='Round',
            y='Smoothed accuracy',
            color='Method',
            facet_col='Setting',
            markers=True,
            template='plotly_white',
            title=f'{dataset_label}: smoothed dynamic-epoch oracle accuracy',
            labels={'Smoothed accuracy': 'MMLU accuracy (%)'},
            category_orders={'Method': ['Linear FLoRA', 'Nonlinear FLoRA', 'Nonlinear FFA'], 'Setting': ['Homo', 'Heter']},
            hover_data={
                'Oracle epochs': True,
                'Oracle accuracy': ':.2f',
                'Smoothed epochs': True,
                'Oracle gain over current epoch': ':.2f',
                'Meaningful switch': True,
            },
        )
        fig_accuracy.update_layout(width=1000, height=400, legend_title_text='')
        fig_accuracy.update_xaxes(dtick=1, showgrid=True, gridcolor='#d9d9d9', gridwidth=1)
        fig_accuracy.update_yaxes(showgrid=True, gridcolor='#d9d9d9', gridwidth=1)
        fig_accuracy.for_each_annotation(lambda annotation: annotation.update(text=annotation.text.split('=')[-1]))
        png_path = _write_dynamic_plot(fig_accuracy, DYNAMIC_EPOCH_DIR / f'{_dynamic_slug(dataset_label)}_accuracy', dynamic_png_warnings)
        if png_path is not None:
            saved_dynamic_png.append(png_path)
        fig_accuracy.show()


    if saved_dynamic_png:
        print(f'Wrote {len(saved_dynamic_png)} dynamic oracle PNG files under {DYNAMIC_EPOCH_DIR}.')
    if dynamic_png_warnings:
        print('Dynamic oracle PNG export skipped or incomplete. Install/enable kaleido for static PNG export.')
        print(f'First dynamic PNG export warning: {dynamic_png_warnings[0]}')

,Method,Dataset label,Setting,Smoothed schedule,Meaningful switches,Max smoothed accuracy,Follow-up experiment suggestion
8,Linear FLoRA,Dolly,Heter,r1-2: e2; r3-4: e3; r5-10: e2,2,29.96,Test a staged schedule; switches may reflect r...
0,Nonlinear FFA,Dolly,Heter,r1-4: e5; r5-7: e3; r8: e2; r9: e5; r10: e2,4,29.05,Test high-local-epoch warmup followed by lower...
16,Nonlinear FLoRA,Dolly,Heter,r1: e5; r2-3: e3; r4-8: e2; r9-10: e1,3,31.06,Test high-local-epoch warmup followed by lower...
9,Linear FLoRA,Dolly,Homo,r1: e2; r2-3: e3; r4: e5; r5-10: e2,3,31.03,Test a staged schedule; switches may reflect r...
1,Nonlinear FFA,Dolly,Homo,r1-2: e5; r3: e2; r4-8: e5; r9-10: e2,3,30.87,Test high-local-epoch warmup followed by lower...
17,Nonlinear FLoRA,Dolly,Homo,r1: e5; r2-5: e3; r6: e5; r7-10: e2,3,30.22,Test high-local-epoch warmup followed by lower...
10,Linear FLoRA,Dolly stratified,Heter,r1: e5; r2: e3; r3-4: e5; r5: e2; r6-7: e3; r8...,6,29.11,Test high-local-epoch warmup followed by lower...
2,Nonlinear FFA,Dolly stratified,Heter,r1-2: e5; r3: e3; r4-5: e5; r6: e3; r7: e5; r8...,6,29.46,Test a staged schedule; switches may reflect r...
18,Nonlinear FLoRA,Dolly stratified,Heter,r1: e5; r2-3: e3; r4: e2; r5-6: e3; r7-10: e1,4,30.10,Test high-local-epoch warmup followed by lower...
11,Linear FLoRA,Dolly stratified,Homo,r1-5: e5; r6: e2; r7: e5; r8-9: e3; r10: e5,4,29.61,Test a staged schedule; switches may reflect r...
3,Nonlinear FFA,Dolly stratified,Homo,r1-2: e5; r3: e3; r4: e2; r5-8: e3; r9: e5; r1...,5,31.26,Test high-local-epoch warmup followed by lower...
19,Nonlinear FLoRA,Dolly stratified,Homo,r1: e5; r2-3: e3; r4-8: e2; r9: e3; r10: e5,4,29.71,Test a staged schedule; switches may reflect r...
12,Linear FLoRA,Wizard,Heter,r1-2: e3; r3-10: e2,1,46.22,Test high-local-epoch warmup followed by lower...
4,Nonlinear FFA,Wizard,Heter,r1-3: e5; r4-5: e2; r6-10: e1,2,33.63,Test high-local-epoch warmup followed by lower...
20,Nonlinear FLoRA,Wizard,Heter,r1-2: e3; r3-10: e2,1,44.13,Test high-local-epoch warmup followed by lower...
13,Linear FLoRA,Wizard,Homo,r1: e1; r2-10: e2,1,45.10,Test lower-epoch warmup followed by higher loc...
5,Nonlinear FFA,Wizard,Homo,r1-2: e2; r3-4: e1; r5-7: e2; r8-9: e1; r10: e2,4,31.50,Test a staged schedule; switches may reflect r...
21,Nonlinear FLoRA,Wizard,Homo,r1-7: e2; r8-10: e1,1,42.02,Test high-local-epoch warmup followed by lower...
14,Linear FLoRA,Wizard stratified,Heter,r1: e3; r2-5: e1; r6-10: e2,2,45.74,Test high-local-epoch warmup followed by lower...
6,Nonlinear FFA,Wizard stratified,Heter,r1-3: e5; r4-5: e2; r6-7: e3; r8: e1; r9: e5; ...,5,33.37,Test high-local-epoch warmup followed by lower...
22,Nonlinear FLoRA,Wizard stratified,Heter,r1: e3; r2-10: e2,1,45.38,Test high-local-epoch warmup followed by lower...
15,Linear FLoRA,Wizard stratified,Homo,r1-2: e1; r3-10: e2,1,46.74,Test lower-epoch warmup followed by higher loc...
7,Nonlinear FFA,Wizard stratified,Homo,r1: e5; r2: e2; r3: e5; r4: e1; r5: e2; r6-7: ...,7,32.35,Test high-local-epoch warmup followed by lower...
23,Nonlinear FLoRA,Wizard stratified,Homo,r1: e3; r2-10: e2,1,42.88,Test high-local-epoch warmup followed by lower...

Dynamic oracle PNG export skipped or incomplete. Install/enable kaleido for static PNG export.
First dynamic PNG export warning: Kaleido requires Google Chrome to be installed.

## Paper Baseline Comparison

The Wizard and Dolly paper baselines are taken from `flora_results_analysis.ipynb`. Paper results are plotted only at their reported communication round, not as horizontal lines across all rounds. Dolly tuning here uses the stratified split, so the Dolly paper point is contextual rather than an exact split-matched baseline.

In [38]:
# paper_comparison = compare_selected_to_paper(tuning_selected)
# if paper_comparison.empty:
#     print('No paper baselines matched the selected tuning rows.')
# else:
#     paper_comparison.to_csv(OUTPUT_DIR / 'tuning_vs_paper.csv', index=False)
#     display(paper_comparison.round(2))

## Round Curves

The fixed-epoch method comparison plots answer the direct question: at local epoch 1, 2, 3, or 5, which method has the better round curve? The all-curve overview plots stay separate so the main comparison stays readable. I would avoid overlaying Dolly and Dolly stratified in this same view because it doubles the curve count and makes the method comparison harder to read; a split-focused view should be faceted by split if we want to inspect that question.

In [39]:
METHOD_ORDER = ['Linear FLoRA', 'Nonlinear FLoRA', 'Nonlinear FFA']
SETTING_ORDER = ['Homo', 'Heter']
RUN_STATUS_ORDER = ['Complete', 'Censored partial', 'Partial log', 'Live partial']
RUN_STATUS_LINE_DASH_MAP = {'Complete': 'solid', 'Censored partial': 'dash', 'Partial log': 'dot', 'Live partial': 'dash'}
RUN_STATUS_SYMBOL_MAP = {'Complete': 'circle', 'Censored partial': 'diamond', 'Partial log': 'x', 'Live partial': 'diamond'}
METHOD_LINE_DASH_MAP = {
    'Linear FLoRA': 'solid',
    'Nonlinear FLoRA': 'solid',
    'Nonlinear FFA': 'dot',
}


def _slug(value):
    return str(value).lower().replace(' ', '_').replace('-', '_').replace('/', '_')


def _sorted_unique_ints(values):
    return sorted({int(value) for value in values})


def _category_orders(data):
    orders = {
        'Method': [method for method in METHOD_ORDER if method in set(data['Method'])],
        'Setting': [setting for setting in SETTING_ORDER if setting in set(data['Setting'])],
        'Local epochs': [str(epoch) for epoch in _sorted_unique_ints(data['Local epochs'])],
    }
    if 'Run status' in data.columns:
        orders['Run status'] = [status for status in RUN_STATUS_ORDER if status in set(data['Run status'])]
    return orders


def _format_facet_labels(fig):
    fig.for_each_annotation(lambda annotation: annotation.update(text=annotation.text.split('=')[-1]))


def _clean_trace_names(fig):
    suffixes = [f', {status}' for status in RUN_STATUS_ORDER]
    for trace in fig.data:
        for suffix in suffixes:
            if trace.name.endswith(suffix):
                trace.name = trace.name[:-len(suffix)]
                break


def _save_plot(fig, output_stem, png_warnings):
    output_stem.parent.mkdir(parents=True, exist_ok=True)
    fig.write_html(output_stem.with_suffix('.html'), include_plotlyjs='cdn')
    png_path = output_stem.with_suffix('.png')
    try:
        fig.write_image(png_path, scale=2)
    except Exception as exc:
        png_path = None
        message = str(exc).strip() or type(exc).__name__
        png_warnings.append(message.splitlines()[0])
    return png_path


def make_epoch_method_comparison(summary, dataset, epoch):
    data = summary[
        (summary['Dataset'] == dataset)
        & (summary['Local epochs'].astype(int) == int(epoch))
    ].copy()
    if data.empty:
        return None

    data = data.sort_values(['Model', 'Setting', 'Method', 'Round'])
    dataset_label = data['Dataset label'].iloc[0]
    model_label = ', '.join(sorted(data['Model'].unique()))
    facet_row = 'Model' if data['Model key'].nunique() > 1 else None
    use_run_status = 'Run status' in data.columns
    hover_data = {
        'Local epochs': True,
        'Std accuracy': ':.2f',
        'Seed count': True,
    }
    if use_run_status:
        hover_data['Run status'] = True
    if 'Result source' in data.columns:
        hover_data['Result source'] = True

    fig = px.line(
        data,
        x='Round',
        y='Mean accuracy',
        color='Method',
        line_dash='Run status' if use_run_status else None,
        symbol='Run status' if use_run_status else None,
        facet_col='Setting',
        facet_row=facet_row,
        markers=True,
        template='plotly_white',
        title=f'{dataset_label} {model_label} epoch {epoch}: method comparison',
        labels={'Mean accuracy': 'MMLU accuracy (%)'},
        category_orders=_category_orders(data),
        line_dash_map=RUN_STATUS_LINE_DASH_MAP if use_run_status else None,
        symbol_map=RUN_STATUS_SYMBOL_MAP if use_run_status else None,
        hover_data=hover_data,
    )
    fig.update_layout(width=1000, height=400, legend_title_text='')
    fig.update_xaxes(dtick=1, showgrid=True, gridcolor='#d9d9d9', gridwidth=1)
    fig.update_yaxes(showgrid=True, gridcolor='#d9d9d9', gridwidth=1)
    _clean_trace_names(fig)
    _format_facet_labels(fig)
    return fig


def make_dataset_all_curves(summary, dataset):
    data = summary[summary['Dataset'] == dataset].copy()
    if data.empty:
        return None

    data['Local epochs'] = data['Local epochs'].astype(int).astype(str)
    data = data.sort_values(['Model', 'Setting', 'Method', 'Local epochs', 'Round'])
    dataset_label = data['Dataset label'].iloc[0]
    facet_row = 'Model' if data['Model key'].nunique() > 1 else None
    use_run_status = 'Run status' in data.columns
    hover_data = {
        'Std accuracy': ':.2f',
        'Seed count': True,
        'Method': True,
    }
    if use_run_status:
        hover_data['Run status'] = True
    if 'Result source' in data.columns:
        hover_data['Result source'] = True

    fig = px.line(
        data,
        x='Round',
        y='Mean accuracy',
        color='Local epochs',
        line_dash='Method',
        symbol='Run status' if use_run_status else None,
        facet_col='Setting',
        facet_row=facet_row,
        markers=True,
        template='plotly_white',
        title=f'{dataset_label}: all tuning round curves',
        labels={'Mean accuracy': 'MMLU accuracy (%)', 'Local epochs': 'Epochs'},
        category_orders=_category_orders(data),
        line_dash_map=METHOD_LINE_DASH_MAP,
        symbol_map=RUN_STATUS_SYMBOL_MAP if use_run_status else None,
        hover_data=hover_data,
    )
    fig.update_layout(width=1000, height=400, legend_title_text='')
    fig.update_xaxes(dtick=1, showgrid=True, gridcolor='#d9d9d9', gridwidth=1)
    fig.update_yaxes(showgrid=True, gridcolor='#d9d9d9', gridwidth=1)
    _format_facet_labels(fig)
    return fig


plot_summary_for_curves = plot_summary if 'plot_summary' in globals() else tuning_summary
plot_summary_for_curves = _instruction_filter(plot_summary_for_curves)
if plot_summary_for_curves.empty:
    print('No tuning summary to plot.')
else:
    png_warnings = []
    saved_png = []
    datasets = plot_summary_for_curves[['Dataset', 'Dataset label']].drop_duplicates().sort_values('Dataset label')
    epochs = _sorted_unique_ints(plot_summary_for_curves['Local epochs'])

    comparison_root = ROUND_CURVE_DIR / 'fixed_epoch_method_comparisons'
    overview_root = ROUND_CURVE_DIR / 'all_curves'

    print('Fixed-epoch method comparisons')
    for _, dataset_row in datasets.iterrows():
        dataset = dataset_row['Dataset']
        dataset_label = dataset_row['Dataset label']
        dataset_dir = comparison_root / _slug(dataset_label)
        for epoch in epochs:
            fig = make_epoch_method_comparison(plot_summary_for_curves, dataset, epoch)
            if fig is None:
                print(f'No data for {dataset_label} epoch {epoch}; skipping.')
                continue
            png_path = _save_plot(fig, dataset_dir / f'epoch_{epoch}', png_warnings)
            if png_path is not None:
                saved_png.append(png_path)
            print(f'{dataset_label} epoch {epoch}')
            fig.show()

    print('All-curve dataset overviews')
    for _, dataset_row in datasets.iterrows():
        dataset = dataset_row['Dataset']
        dataset_label = dataset_row['Dataset label']
        fig = make_dataset_all_curves(plot_summary_for_curves, dataset)
        if fig is None:
            continue
        png_path = _save_plot(fig, overview_root / _slug(dataset_label), png_warnings)
        if png_path is not None:
            saved_png.append(png_path)
        print(dataset_label)
        fig.show()

    if saved_png:
        print(f'Wrote {len(saved_png)} PNG files under {ROUND_CURVE_DIR}.')
    if png_warnings:
        print('PNG export skipped or incomplete. Install/enable kaleido for static PNG export.')
        print(f'First PNG export warning: {png_warnings[0]}')

Fixed-epoch method comparisons
Dolly epoch 1

Dolly epoch 2

Dolly epoch 3

Dolly epoch 5

Dolly stratified epoch 1

Dolly stratified epoch 2

Dolly stratified epoch 3

Dolly stratified epoch 5

Wizard epoch 1

Wizard epoch 2

Wizard epoch 3

Wizard epoch 5

Wizard stratified epoch 1

Wizard stratified epoch 2

Wizard stratified epoch 3

Wizard stratified epoch 5

All-curve dataset overviews
Dolly

Dolly stratified

Wizard

Wizard stratified

PNG export skipped or incomplete. Install/enable kaleido for static PNG export.
First PNG export warning: Kaleido requires Google Chrome to be installed.

## RTE RoBERTa Tuning

This independent section reloads the RTE stratified RoBERTa-base epoch/round sweep and keeps it out of the TinyLlama instruction-dataset tables above. It reports coverage, selected epoch/round pairs, and the same fixed-epoch and all-curve tuning views used for the instruction datasets.

In [40]:
RTE_DATASET = 'rte_stratified'
RTE_MODEL_KEY = 'roberta-base'
RTE_OUTPUT_DIR = OUTPUT_DIR / 'rte_stratified_roberta'
RTE_CURVE_DIR = ROUND_CURVE_DIR / 'rte_stratified_roberta'
RTE_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
RTE_CURVE_DIR.mkdir(parents=True, exist_ok=True)

rte_complete_scores = load_tuning_results([BASE_DIR / 'epoch_round_tuning'], complete_only=True)
if rte_complete_scores.empty:
    rte_scores = rte_complete_scores.copy()
else:
    rte_scores = rte_complete_scores[
        (rte_complete_scores['Dataset'] == RTE_DATASET)
        & (rte_complete_scores['Model key'] == RTE_MODEL_KEY)
    ].copy()

if rte_scores.empty:
    print('No complete RTE stratified RoBERTa-base tuning runs found.')
else:
    rte_summary = summarize_tuning_results(rte_scores)
    rte_plateaus, rte_selected = select_plateaus(rte_summary, tolerance=NEAR_BEST_TOLERANCE)
    rte_curve_diagnostics, rte_optimal_epoch_round_pairs, rte_marginal_round_gains = compute_epoch_round_selection_metrics(
        rte_summary,
        plateaus=rte_plateaus,
        selected_pairs=rte_selected,
        tolerance=NEAR_BEST_TOLERANCE,
    )

    rte_status = (
        rte_scores.groupby(
            [
                'Method key',
                'Method',
                'Dataset',
                'Dataset label',
                'Model key',
                'Model',
                'Setting key',
                'Setting',
                'Local epochs',
                'Config rounds',
                'Seed',
            ],
            dropna=False,
        )
        .agg(
            **{
                'Observed rounds': ('Round', 'max'),
                'Score rows': ('Round', 'size'),
                'Run status': ('Run status', 'first'),
                'Result source': ('Result source', 'first'),
                'Run dir': ('Run dir', 'first'),
            }
        )
        .reset_index()
    )
    rte_status['Complete run'] = rte_status['Observed rounds'].astype(int) >= rte_status['Config rounds'].astype(int)

    rte_coverage = (
        rte_status.groupby(['Method', 'Setting'], sort=False)
        .agg(
            **{
                'Epochs': ('Local epochs', lambda values: ', '.join(str(int(value)) for value in sorted(set(values)))),
                'Complete runs': ('Complete run', 'sum'),
                'Total runs': ('Complete run', 'size'),
                'Min observed rounds': ('Observed rounds', 'min'),
                'Max observed rounds': ('Observed rounds', 'max'),
                'Result source': ('Result source', lambda values: ', '.join(sorted(set(map(str, values))))),
            }
        )
        .reset_index()
    )

    rte_best_by_method_setting = (
        rte_summary.loc[
            rte_summary.groupby(['Method', 'Setting'], sort=False)['Mean accuracy'].idxmax(),
            ['Method', 'Setting', 'Local epochs', 'Round', 'Mean accuracy', 'Run status', 'Result source'],
        ]
        .rename(
            columns={
                'Local epochs': 'Best epochs',
                'Round': 'Best round',
                'Mean accuracy': 'Best accuracy',
            }
        )
        .sort_values(['Setting', 'Method'])
        .reset_index(drop=True)
    )

    rte_scores.to_csv(RTE_OUTPUT_DIR / 'tuning_scores.csv', index=False)
    rte_summary.to_csv(RTE_OUTPUT_DIR / 'tuning_summary.csv', index=False)
    rte_status.to_csv(RTE_OUTPUT_DIR / 'run_status.csv', index=False)
    rte_coverage.to_csv(RTE_OUTPUT_DIR / 'coverage.csv', index=False)
    rte_plateaus.to_csv(RTE_OUTPUT_DIR / 'tuning_plateaus.csv', index=False)
    rte_selected.to_csv(RTE_OUTPUT_DIR / 'tuning_selected.csv', index=False)
    rte_curve_diagnostics.to_csv(RTE_OUTPUT_DIR / 'epoch_round_curve_diagnostics.csv', index=False)
    rte_optimal_epoch_round_pairs.to_csv(RTE_OUTPUT_DIR / 'epoch_round_optimal_pairs.csv', index=False)
    rte_marginal_round_gains.to_csv(RTE_OUTPUT_DIR / 'epoch_round_marginal_gains.csv', index=False)
    rte_best_by_method_setting.to_csv(RTE_OUTPUT_DIR / 'best_by_method_setting.csv', index=False)

    print(f'Loaded {len(rte_scores)} per-round RTE scores from {rte_scores["Run dir"].nunique()} complete runs.')
    print(f'Wrote RTE CSV summaries to {RTE_OUTPUT_DIR}.')
    display(rte_coverage.round(2))
    display(rte_best_by_method_setting.round(2))
    display(rte_selected.round(2))

    def make_rte_epoch_method_comparison(summary, epoch):
        data = summary[
            (summary['Dataset'] == RTE_DATASET)
            & (summary['Model key'] == RTE_MODEL_KEY)
            & (summary['Local epochs'].astype(int) == int(epoch))
        ].copy()
        if data.empty:
            return None

        data = data.sort_values(['Setting', 'Method', 'Round'])
        dataset_label = data['Dataset label'].iloc[0]
        model_label = data['Model'].iloc[0]
        use_run_status = 'Run status' in data.columns
        hover_data = {
            'Local epochs': True,
            'Std accuracy': ':.2f',
            'Seed count': True,
        }
        if use_run_status:
            hover_data['Run status'] = True
        if 'Result source' in data.columns:
            hover_data['Result source'] = True

        fig = px.line(
            data,
            x='Round',
            y='Mean accuracy',
            color='Method',
            line_dash='Run status' if use_run_status else None,
            symbol='Run status' if use_run_status else None,
            facet_col='Setting',
            markers=True,
            template='plotly_white',
            title=f'{dataset_label} {model_label} epoch {epoch}: method comparison',
            labels={'Mean accuracy': 'RTE accuracy (%)'},
            category_orders=_category_orders(data),
            line_dash_map=RUN_STATUS_LINE_DASH_MAP if use_run_status else None,
            symbol_map=RUN_STATUS_SYMBOL_MAP if use_run_status else None,
            hover_data=hover_data,
        )
        fig.update_layout(width=1000, height=400, legend_title_text='')
        fig.update_xaxes(dtick=1, showgrid=True, gridcolor='#d9d9d9', gridwidth=1)
        fig.update_yaxes(showgrid=True, gridcolor='#d9d9d9', gridwidth=1)
        _clean_trace_names(fig)
        _format_facet_labels(fig)
        return fig

    def make_rte_all_curves(summary):
        data = summary[(summary['Dataset'] == RTE_DATASET) & (summary['Model key'] == RTE_MODEL_KEY)].copy()
        if data.empty:
            return None

        data['Local epochs'] = data['Local epochs'].astype(int).astype(str)
        data = data.sort_values(['Setting', 'Method', 'Local epochs', 'Round'])
        dataset_label = data['Dataset label'].iloc[0]
        model_label = data['Model'].iloc[0]
        use_run_status = 'Run status' in data.columns
        hover_data = {
            'Std accuracy': ':.2f',
            'Seed count': True,
            'Method': True,
        }
        if use_run_status:
            hover_data['Run status'] = True
        if 'Result source' in data.columns:
            hover_data['Result source'] = True

        fig = px.line(
            data,
            x='Round',
            y='Mean accuracy',
            color='Local epochs',
            line_dash='Method',
            symbol='Run status' if use_run_status else None,
            facet_col='Setting',
            markers=True,
            template='plotly_white',
            title=f'{dataset_label} {model_label}: all tuning round curves',
            labels={'Mean accuracy': 'RTE accuracy (%)', 'Local epochs': 'Epochs'},
            category_orders=_category_orders(data),
            line_dash_map=METHOD_LINE_DASH_MAP,
            symbol_map=RUN_STATUS_SYMBOL_MAP if use_run_status else None,
            hover_data=hover_data,
        )
        fig.update_layout(width=1000, height=400, legend_title_text='')
        fig.update_xaxes(dtick=1, showgrid=True, gridcolor='#d9d9d9', gridwidth=1)
        fig.update_yaxes(showgrid=True, gridcolor='#d9d9d9', gridwidth=1)
        _format_facet_labels(fig)
        return fig

    rte_png_warnings = []
    rte_saved_png = []
    rte_epochs = _sorted_unique_ints(rte_summary['Local epochs'])
    rte_comparison_root = RTE_CURVE_DIR / 'fixed_epoch_method_comparisons'

    print('RTE fixed-epoch method comparisons')
    for epoch in rte_epochs:
        fig = make_rte_epoch_method_comparison(rte_summary, epoch)
        if fig is None:
            continue
        png_path = _save_plot(fig, rte_comparison_root / f'epoch_{epoch}', rte_png_warnings)
        if png_path is not None:
            rte_saved_png.append(png_path)
        print(f'RTE stratified RoBERTa-base epoch {epoch}')
        fig.show()

    print('RTE all-curve overview')
    fig = make_rte_all_curves(rte_summary)
    if fig is not None:
        png_path = _save_plot(fig, RTE_CURVE_DIR / 'all_curves' / 'rte_stratified_roberta', rte_png_warnings)
        if png_path is not None:
            rte_saved_png.append(png_path)
        fig.show()

    if rte_saved_png:
        print(f'Wrote {len(rte_saved_png)} RTE PNG files under {RTE_CURVE_DIR}.')
    if rte_png_warnings:
        print('RTE PNG export skipped or incomplete. Install/enable kaleido for static PNG export.')
        print(f'First RTE PNG export warning: {rte_png_warnings[0]}')

Loaded 300 per-round RTE scores from 30 complete runs.
Wrote RTE CSV summaries to tuning_analysis_outputs/rte_stratified_roberta.

,Method,Setting,Epochs,Complete runs,Total runs,Min observed rounds,Max observed rounds,Result source
0,Nonlinear FFA,Heter,"1, 2, 3, 5, 8",5,5,10,10,score log
1,Nonlinear FFA,Homo,"1, 2, 3, 5, 8",5,5,10,10,score log
2,Linear FLoRA,Heter,"1, 2, 3, 5, 8",5,5,10,10,score log
3,Linear FLoRA,Homo,"1, 2, 3, 5, 8",5,5,10,10,score log
4,Nonlinear FLoRA,Heter,"1, 2, 3, 5, 8",5,5,10,10,score log
5,Nonlinear FLoRA,Homo,"1, 2, 3, 5, 8",5,5,10,10,score log

,Method,Setting,Best epochs,Best round,Best accuracy,Run status,Result source
0,Linear FLoRA,Heter,8,10,60.65,Complete,score log
1,Nonlinear FFA,Heter,8,1,58.48,Complete,score log
2,Nonlinear FLoRA,Heter,8,7,61.37,Complete,score log
3,Linear FLoRA,Homo,5,10,62.09,Complete,score log
4,Nonlinear FFA,Homo,2,5,58.48,Complete,score log
5,Nonlinear FLoRA,Homo,8,2,59.57,Complete,score log

,Method key,Method,Dataset,Dataset label,Model key,Model,Setting key,Setting,Selected epochs,Selected round,Selected accuracy,Selected std,Selected seed count,Selected seeds,Selected compute cost,Best epochs,Best round,Best accuracy,Accuracy gap to best,Low-cost tie count
0,ffa,Nonlinear FFA,rte_stratified,RTE stratified,roberta-base,RoBERTa-base,heter,Heter,8,1,58.48,0.0,1,0,8,8,1,58.48,0.00,1
1,ffa,Nonlinear FFA,rte_stratified,RTE stratified,roberta-base,RoBERTa-base,homo,Homo,8,1,57.76,0.0,1,0,8,2,5,58.48,0.72,1
2,flora,Linear FLoRA,rte_stratified,RTE stratified,roberta-base,RoBERTa-base,heter,Heter,8,10,60.65,0.0,1,0,80,8,10,60.65,0.00,1
3,flora,Linear FLoRA,rte_stratified,RTE stratified,roberta-base,RoBERTa-base,homo,Homo,5,9,61.37,0.0,1,0,45,5,10,62.09,0.72,1
4,nonlinear_flora,Nonlinear FLoRA,rte_stratified,RTE stratified,roberta-base,RoBERTa-base,heter,Heter,8,7,61.37,0.0,1,0,56,8,7,61.37,0.00,1
5,nonlinear_flora,Nonlinear FLoRA,rte_stratified,RTE stratified,roberta-base,RoBERTa-base,homo,Homo,8,2,59.57,0.0,1,0,16,8,2,59.57,0.00,1

RTE fixed-epoch method comparisons
RTE stratified RoBERTa-base epoch 1

RTE stratified RoBERTa-base epoch 2

RTE stratified RoBERTa-base epoch 3

RTE stratified RoBERTa-base epoch 5

RTE stratified RoBERTa-base epoch 8

RTE all-curve overview

RTE PNG export skipped or incomplete. Install/enable kaleido for static PNG export.
First RTE PNG export warning: Kaleido requires Google Chrome to be installed.

## Stratified vs Non-Stratified Curves

These plots compare the original and stratified versions of each dataset family while holding method, setting, and local epoch count fixed. The overlay plots show the raw curves; the delta plots show `stratified - non-stratified` MMLU accuracy at each communication round. A delta near zero means stratification barely changed that curve, while a larger positive or negative delta means the split changed the training trajectory.

In [43]:
# SPLIT_COMPARISON_DIR = ROUND_CURVE_DIR / 'split_comparisons'
# SPLIT_COMPARISON_DIR.mkdir(parents=True, exist_ok=True)
# SPLIT_PAIRS = [
#     {
#         'Dataset family': 'Dolly',
#         'Non-stratified dataset': 'dolly',
#         'Stratified dataset': 'dolly_stratified',
#     },
#     {
#         'Dataset family': 'Wizard',
#         'Non-stratified dataset': 'wiz',
#         'Stratified dataset': 'wiz_stratified',
#     },
# ]
# SPLIT_LABELS = {
#     'non_stratified': 'Non-stratified',
#     'stratified': 'Stratified',
# }
# SPLIT_LINE_DASH_MAP = {
#     'Non-stratified': 'solid',
#     'Stratified': 'dash',
# }


# def _split_comparison_data(summary, dataset_pair, epoch):
#     data = summary[
#         summary['Dataset'].isin([
#             dataset_pair['Non-stratified dataset'],
#             dataset_pair['Stratified dataset'],
#         ])
#         & (summary['Local epochs'].astype(int) == int(epoch))
#     ].copy()
#     if data.empty:
#         return data

#     split_by_dataset = {
#         dataset_pair['Non-stratified dataset']: SPLIT_LABELS['non_stratified'],
#         dataset_pair['Stratified dataset']: SPLIT_LABELS['stratified'],
#     }
#     data['Dataset family'] = dataset_pair['Dataset family']
#     data['Split'] = data['Dataset'].map(split_by_dataset)
#     return data.sort_values(['Method', 'Setting', 'Split', 'Round'])


# def _split_delta_data(summary, dataset_pair, epoch):
#     data = _split_comparison_data(summary, dataset_pair, epoch)
#     if data.empty:
#         return data

#     value_columns = ['Method', 'Setting', 'Local epochs', 'Round', 'Split']
#     pivot = data[value_columns + ['Mean accuracy']].pivot_table(
#         index=['Method', 'Setting', 'Local epochs', 'Round'],
#         columns='Split',
#         values='Mean accuracy',
#         aggfunc='mean',
#     ).reset_index()
#     required = [SPLIT_LABELS['non_stratified'], SPLIT_LABELS['stratified']]
#     if not all(column in pivot.columns for column in required):
#         return pd.DataFrame()

#     pivot = pivot.dropna(subset=required).copy()
#     if pivot.empty:
#         return pivot

#     pivot['Dataset family'] = dataset_pair['Dataset family']
#     pivot['Stratified - non-stratified'] = (
#         pivot[SPLIT_LABELS['stratified']] - pivot[SPLIT_LABELS['non_stratified']]
#     )
#     pivot['Absolute deviation'] = pivot['Stratified - non-stratified'].abs()
#     return pivot.sort_values(['Method', 'Setting', 'Round'])


# def make_split_curve_comparison(summary, dataset_pair, epoch):
#     data = _split_comparison_data(summary, dataset_pair, epoch)
#     if data.empty:
#         return None

#     use_run_status = 'Run status' in data.columns
#     hover_data = {
#         'Dataset label': True,
#         'Std accuracy': ':.2f',
#         'Seed count': True,
#     }
#     if use_run_status:
#         hover_data['Run status'] = True
#     if 'Result source' in data.columns:
#         hover_data['Result source'] = True

#     fig = px.line(
#         data,
#         x='Round',
#         y='Mean accuracy',
#         color='Split',
#         line_dash='Split',
#         facet_row='Method',
#         facet_col='Setting',
#         markers=True,
#         template='plotly_white',
#         title=f"{dataset_pair['Dataset family']} epoch {epoch}: stratified vs non-stratified curves",
#         labels={'Mean accuracy': 'MMLU accuracy (%)'},
#         category_orders={
#             'Split': [SPLIT_LABELS['non_stratified'], SPLIT_LABELS['stratified']],
#             'Method': [method for method in METHOD_ORDER if method in set(data['Method'])],
#             'Setting': [setting for setting in SETTING_ORDER if setting in set(data['Setting'])],
#         },
#         line_dash_map=SPLIT_LINE_DASH_MAP,
#         hover_data=hover_data,
#     )
#     fig.update_layout(width=1100, height=820, legend_title_text='')
#     fig.update_xaxes(dtick=1, showgrid=True, gridcolor='#d9d9d9', gridwidth=1)
#     fig.update_yaxes(showgrid=True, gridcolor='#d9d9d9', gridwidth=1)
#     _format_facet_labels(fig)
#     return fig


# def make_split_delta_comparison(summary, dataset_pair, epoch):
#     data = _split_delta_data(summary, dataset_pair, epoch)
#     if data.empty:
#         return None

#     fig = px.line(
#         data,
#         x='Round',
#         y='Stratified - non-stratified',
#         color='Method',
#         facet_col='Setting',
#         markers=True,
#         template='plotly_white',
#         title=f"{dataset_pair['Dataset family']} epoch {epoch}: stratified minus non-stratified accuracy",
#         labels={'Stratified - non-stratified': 'Accuracy delta (pp)'},
#         category_orders={
#             'Method': [method for method in METHOD_ORDER if method in set(data['Method'])],
#             'Setting': [setting for setting in SETTING_ORDER if setting in set(data['Setting'])],
#         },
#         hover_data={
#             SPLIT_LABELS['non_stratified']: ':.2f',
#             SPLIT_LABELS['stratified']: ':.2f',
#             'Absolute deviation': ':.2f',
#         },
#     )
#     fig.add_hline(y=0, line_width=1, line_dash='dash', line_color='#6b7280')
#     fig.update_layout(width=1000, height=400, legend_title_text='')
#     fig.update_xaxes(dtick=1, showgrid=True, gridcolor='#d9d9d9', gridwidth=1)
#     fig.update_yaxes(showgrid=True, gridcolor='#d9d9d9', gridwidth=1)
#     _format_facet_labels(fig)
#     return fig


# def build_split_deviation_summary(summary):
#     rows = []
#     for dataset_pair in SPLIT_PAIRS:
#         for epoch in _sorted_unique_ints(summary['Local epochs']):
#             delta_data = _split_delta_data(summary, dataset_pair, epoch)
#             if delta_data.empty:
#                 continue
#             for group_values, group in delta_data.groupby(['Dataset family', 'Method', 'Setting', 'Local epochs'], sort=False):
#                 final_row = group.sort_values('Round').iloc[-1]
#                 rows.append(
#                     dict(zip(['Dataset family', 'Method', 'Setting', 'Local epochs'], group_values))
#                     | {
#                         'Compared rounds': int(group['Round'].nunique()),
#                         'Mean signed delta': float(group['Stratified - non-stratified'].mean()),
#                         'Mean absolute deviation': float(group['Absolute deviation'].mean()),
#                         'Max absolute deviation': float(group['Absolute deviation'].max()),
#                         'Final-round delta': float(final_row['Stratified - non-stratified']),
#                     }
#                 )
#     if not rows:
#         return pd.DataFrame()
#     return pd.DataFrame(rows).sort_values(['Dataset family', 'Setting', 'Method', 'Local epochs'])


# split_summary_for_plots = plot_summary if 'plot_summary' in globals() else tuning_summary
# split_summary_for_plots = _instruction_filter(split_summary_for_plots)
# split_delta_source = tuning_summary
# split_deviation_summary = build_split_deviation_summary(split_delta_source)
# split_deviation_summary.to_csv(OUTPUT_DIR / 'split_stratification_deviation_summary.csv', index=False)

# if split_deviation_summary.empty:
#     print('No matched stratified/non-stratified curves available.')
# else:
#     print('Stratified vs non-stratified deviation summary from complete runs')
#     display(split_deviation_summary.round(2))

# split_png_warnings = []
# split_saved_png = []
# for dataset_pair in SPLIT_PAIRS:
#     family_dir = SPLIT_COMPARISON_DIR / _slug(dataset_pair['Dataset family'])
#     for epoch in _sorted_unique_ints(split_summary_for_plots['Local epochs']):
#         curve_fig = make_split_curve_comparison(split_summary_for_plots, dataset_pair, epoch)
#         if curve_fig is not None:
#             png_path = _save_plot(curve_fig, family_dir / f'epoch_{epoch}_curves', split_png_warnings)
#             if png_path is not None:
#                 split_saved_png.append(png_path)
#             print(f"{dataset_pair['Dataset family']} epoch {epoch}: split curve overlay")
#             curve_fig.show()

#         # delta_fig = make_split_delta_comparison(split_delta_source, dataset_pair, epoch)
#         # if delta_fig is not None:
#         #     png_path = _save_plot(delta_fig, family_dir / f'epoch_{epoch}_delta', split_png_warnings)
#         #     if png_path is not None:
#         #         split_saved_png.append(png_path)
#         #     print(f"{dataset_pair['Dataset family']} epoch {epoch}: stratified-minus-nonstratified delta")
#         #     delta_fig.show()

# if split_saved_png:
#     print(f'Wrote {len(split_saved_png)} split-comparison PNG files under {SPLIT_COMPARISON_DIR}.')
# if split_png_warnings:
#     print('Split-comparison PNG export skipped or incomplete. Install/enable kaleido for static PNG export.')
#     print(f'First split-comparison PNG export warning: {split_png_warnings[0]}')

## Epoch x Round Heatmaps

In [42]:
# if tuning_summary.empty:
#     print('No tuning summary to plot.')
# else:
#     heatmap_cases = (
#         tuning_summary[tuning_summary['Dataset'].isin(INSTRUCTION_DATASETS)][['Method key', 'Dataset', 'Model key', 'Setting key']]
#         .drop_duplicates()
#         .sort_values(['Dataset', 'Model key', 'Setting key', 'Method key'])
#     )
#     heatmap_selected_pairs = optimal_epoch_round_pairs if 'optimal_epoch_round_pairs' in globals() else tuning_selected
#     heatmap_png_warnings = []
#     heatmap_saved_png = []
#     for _, row in heatmap_cases.iterrows():
#         fig = make_tuning_heatmap(
#             tuning_summary,
#             method=row['Method key'],
#             dataset=row['Dataset'],
#             model=row['Model key'],
#             setting=row['Setting key'],
#             selected_pairs=heatmap_selected_pairs,
#             plateaus=tuning_plateaus,
#             show_markers=True,
#             tolerance=NEAR_BEST_TOLERANCE,
#         )
#         if fig is None:
#             continue
#         output_stem = FIGURE_DIR / f"heatmap_{row['Method key']}_{row['Dataset']}_{row['Model key']}_{row['Setting key']}"
#         png_path = _save_plot(fig, output_stem, heatmap_png_warnings)
#         if png_path is not None:
#             heatmap_saved_png.append(png_path)
#         fig.show()
#     if heatmap_saved_png:
#         print(f'Wrote {len(heatmap_saved_png)} annotated heatmap PNG files to {FIGURE_DIR}.')
#     if heatmap_png_warnings:
#         print('Heatmap PNG export skipped or incomplete. Install/enable kaleido for static PNG export.')
#         print(f'First heatmap PNG export warning: {heatmap_png_warnings[0]}')